# SPDX-FileCopyrightText: 2026 Teng Zhang
# SPDX-License-Identifier: MIT
"""Generate a small-strain Standard Linear Solid UMAT."""

from __future__ import annotations

import math
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import coupfe.codegen as au
from coupfe.codegen.core.tensor import eye, trace


class SmallStrainViscoelastic(au.SmallStrainMaterial):
    """Compression-positive SLS with one deviatoric Maxwell branch.

    ``PROPS`` order is ``K, G_inf, G_v, tau``. The viscous strain tensor
    ``eps_v`` occupies ``STATEV(1..9)`` in column-major order.
    """

    props = dict(K=30.0, G_inf=10.0, G_v=5.0, tau=0.5)
    state_vars = dict(eps_v=np.zeros((3, 3)))

    def stress_update(self, sigma_old, strain_old, dstrain, eps_v_old, dt):
        I = eye(3)
        strain_new = strain_old + dstrain
        ratio = dt / self.tau

        dev_e = strain_new - (1.0 / 3.0) * trace(strain_new) * I
        eps_v_new = (eps_v_old + ratio * dev_e) / (1.0 + ratio)
        sigma_new = (
            self.K * trace(strain_new) * I
            + 2.0 * self.G_inf * dev_e
            + 2.0 * self.G_v * (dev_e - eps_v_new)
        )
        return sigma_new, {"eps_v": eps_v_new}


STEP_TENSOR_SHEAR = 0.01
TIME_INCREMENT = 0.1
N_INCREMENTS = 30

_GENERATED_PROVENANCE = """\
C     Declaration origin: tengzhang48/abaqus_ufl small_strain_viscoelastic_umat
C     Commit: 0f525339db1aad70e9f8f4825a02c1164f0da7a0
C     Original declaration Copyright (c) 2026 Teng Zhang, MIT.
C     Regenerated by CoupFE; see README.md for scope and license link.
"""


def discrete_shear_stress(increment_number, material=None):
    """Independent backward-Euler step-shear stress at increment ``n``."""
    mat = SmallStrainViscoelastic() if material is None else material
    ratio = TIME_INCREMENT / mat.tau
    return 2.0 * STEP_TENSOR_SHEAR * (
        mat.G_inf + mat.G_v / (1.0 + ratio) ** increment_number
    )


def discrete_viscous_shear(increment_number, material=None):
    """Independent backward-Euler viscous shear component at ``n``."""
    mat = SmallStrainViscoelastic() if material is None else material
    ratio = TIME_INCREMENT / mat.tau
    return STEP_TENSOR_SHEAR * (
        1.0 - 1.0 / (1.0 + ratio) ** increment_number
    )


def drive_step_shear(model, n_increments=N_INCREMENTS):
    """Apply one tensor-shear step, then hold it for the remaining updates."""
    dstrain = np.zeros((3, 3))
    dstrain[0, 1] = dstrain[1, 0] = STEP_TENSOR_SHEAR
    hold = np.zeros((3, 3))
    sigma = np.zeros((3, 3))
    strain = np.zeros((3, 3))
    eps_v = np.zeros((3, 3))
    stresses = []
    viscous_strains = []
    for index in range(n_increments):
        increment = dstrain if index == 0 else hold
        sigma, state = model.stress_update(
            sigma, strain, increment, eps_v, TIME_INCREMENT
        )
        sigma = np.real(np.asarray(sigma, dtype=complex))
        eps_v = np.real(np.asarray(state["eps_v"], dtype=complex))
        strain = strain + increment
        stresses.append(float(sigma[0, 1]))
        viscous_strains.append(float(eps_v[0, 1]))
    return stresses, viscous_strains


def reference_errors(model=None):
    """Return maximum errors against the discrete relaxation solution."""
    mat = SmallStrainViscoelastic() if model is None else model
    stresses, viscous_strains = drive_step_shear(mat)
    stress_errors = []
    state_errors = []
    for increment_number in range(1, N_INCREMENTS + 1):
        stress_errors.append(abs(
            stresses[increment_number - 1]
            - discrete_shear_stress(increment_number, mat)
        ))
        state_errors.append(abs(
            viscous_strains[increment_number - 1]
            - discrete_viscous_shear(increment_number, mat)
        ))
    return {
        "max_stress_abs": max(stress_errors),
        "max_viscous_strain_abs": max(state_errors),
        "first_stress": stresses[0],
        "final_stress": stresses[-1],
    }


def continuous_limit_errors(material=None):
    """Backward-Euler decay error at two step sizes for fixed total time."""
    mat = SmallStrainViscoelastic() if material is None else material
    total_time = 1.0
    errors = []
    for dt in (0.1, 0.05):
        n_steps = int(round(total_time / dt))
        discrete = 1.0 / (1.0 + dt / mat.tau) ** n_steps
        errors.append(abs(discrete - math.exp(-total_time / mat.tau)))
    return tuple(errors)


def generate(output=None, *, verify=True) -> Path:
    """Verify the model/oracle and generate the Abaqus UMAT."""
    model = SmallStrainViscoelastic()
    if verify:
        if not model.verify(verbose=False):
            raise RuntimeError("Python tangent verification failed")
        errors = reference_errors(model)
        if max(
            errors["max_stress_abs"],
            errors["max_viscous_strain_abs"],
        ) >= 1.0e-12:
            raise RuntimeError(
                "independent relaxation oracle failed: {}".format(errors)
            )

    target = (
        Path(__file__).with_name("small_strain_viscoelastic.for")
        if output is None
        else Path(output)
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    au.generate_small_strain_umat(model, str(target))

    source = target.read_text()
    header_end = "C======================================================================\n"
    if _GENERATED_PROVENANCE not in source:
        source = source.replace(
            header_end, header_end + _GENERATED_PROVENANCE, 1
        )
        target.write_text(source)
    return target


if __name__ == "__main__":
    print("Generated {}".format(generate()))
