# SPDX-FileCopyrightText: 2026 Teng Zhang
# SPDX-License-Identifier: MIT
"""Generate a one-term compressible Ogden finite-strain Abaqus UMAT.

This is a namespace-only port of the project-authored MIT spectral example
released in ``tengzhang48/abaqus_ufl``.  It exercises CoupFE's existing
rotation-safe eigenvalue code-generation path without changing any API.
"""
from __future__ import annotations

from pathlib import Path
import sys
from typing import Optional

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import coupfe.codegen as au
from coupfe.codegen.core.tensor import det, eig, inv, log, sqrt


class OgdenOneTerm(au.Material):
    """One-term compressible Ogden law with ``PROPS = (mu, alpha, K)``."""

    props = dict(mu=1.0, alpha=3.5, K=100.0)

    def stress_PK1(self, F):
        J = det(F)
        C = F.T @ F
        lam, V = eig(C)

        scale = J ** (-1.0 / 3.0)
        lb1 = scale * sqrt(lam[0])
        lb2 = scale * sqrt(lam[1])
        lb3 = scale * sqrt(lam[2])

        w1 = lb1 ** self.alpha
        w2 = lb2 ** self.alpha
        w3 = lb3 ** self.alpha
        mean_w = (w1 + w2 + w3) / 3.0

        coefficient = 2.0 * self.mu / self.alpha
        volumetric = self.K * log(J)
        tau1 = coefficient * (w1 - mean_w) + volumetric
        tau2 = coefficient * (w2 - mean_w) + volumetric
        tau3 = coefficient * (w3 - mean_w) + volumetric

        diagonal = np.array(
            [
                [tau1 / lam[0], 0.0, 0.0],
                [0.0, tau2 / lam[1], 0.0],
                [0.0, 0.0, tau3 / lam[2]],
            ]
        )
        second_pk = V @ diagonal @ inv(V)
        return F @ second_pk


DEFAULT_PROPS = tuple(OgdenOneTerm.props.values())

_GENERATED_PROVENANCE = """\
C     Declaration origin: tengzhang48/abaqus_ufl ogden_umat
C     Commit: 0f525339db1aad70e9f8f4825a02c1164f0da7a0
C     Original declaration Copyright (c) 2026 Teng Zhang, MIT.
C     Regenerated by CoupFE; see README.md for scope and license link.
"""


def verification_state():
    """Return a rotated, sheared, non-isochoric distinct-spectrum state."""

    angles = (0.4, -0.3, 0.7)
    ax, ay, az = angles
    rotation_x = np.array(
        [
            [1.0, 0.0, 0.0],
            [0.0, np.cos(ax), -np.sin(ax)],
            [0.0, np.sin(ax), np.cos(ax)],
        ]
    )
    rotation_y = np.array(
        [
            [np.cos(ay), 0.0, np.sin(ay)],
            [0.0, 1.0, 0.0],
            [-np.sin(ay), 0.0, np.cos(ay)],
        ]
    )
    rotation_z = np.array(
        [
            [np.cos(az), -np.sin(az), 0.0],
            [np.sin(az), np.cos(az), 0.0],
            [0.0, 0.0, 1.0],
        ]
    )
    stretch = np.array(
        [
            [1.15, 0.08, 0.00],
            [0.08, 0.95, 0.05],
            [0.00, 0.05, 1.06],
        ]
    )
    return {"F": rotation_z @ rotation_y @ rotation_x @ stretch}


def generate_source(
    output_dir: Optional[str] = None, *, verify: bool = True
) -> Path:
    """Verify the declaration and emit the self-contained Abaqus UMAT."""

    model = OgdenOneTerm()
    if verify and not model.verify(state=verification_state(), verbose=False):
        raise RuntimeError("Ogden material verification failed")

    out_dir = (
        Path(output_dir)
        if output_dir is not None
        else Path(__file__).resolve().parent
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    output = out_dir / "ogden_umat.for"
    au.generate_umat(model, str(output))

    source = output.read_text()
    header_end = "C======================================================================\n"
    if _GENERATED_PROVENANCE not in source:
        source = source.replace(
            header_end, header_end + _GENERATED_PROVENANCE, 1
        )
        output.write_text(source)
    return output


if __name__ == "__main__":
    print("Generated {}".format(generate_source()))
