C======================================================================
C     Generated by coupfe.codegen v0.1.0
C     Material: NeoHookean
C     Fields: u
C     Element: Hex8, NDOFEL = 24, F-bar = ON
C======================================================================

C======================================================================
C     Section 1: coupfe_element_rk subroutine (native entry point)
C======================================================================

C======================================================================
C     coupfe_element_rk subroutine — generated by coupfe.codegen (F-bar Hex8)
C     Material: NeoHookean
C     Fields: u
C     Element: Hex8, NDOFEL = 24, F-bar = ON
C======================================================================
      SUBROUTINE coupfe_element_rk(COORDS, U, DU, PROPS,
     &  SVARS_IN, R, K, SVARS_OUT, TIME, DTIME)

      IMPLICIT NONE

C     --- CoupFE native element interface ---
      INTEGER, PARAMETER :: ndim = 3
      INTEGER, PARAMETER :: NNODE_E = 8
      INTEGER, PARAMETER :: NGP = 8
      INTEGER, PARAMETER :: NDOFEL = 24
      INTEGER, PARAMETER :: NPROPS = 2
      INTEGER, PARAMETER :: NSVARS = 1
      INTEGER, PARAMETER :: MCRD = 3



      DOUBLE PRECISION, INTENT(IN) :: COORDS(MCRD,NNODE_E)
      DOUBLE PRECISION, INTENT(IN) :: U(NDOFEL), DU(NDOFEL)
      DOUBLE PRECISION, INTENT(IN) :: PROPS(NPROPS)
      DOUBLE PRECISION, INTENT(IN) :: SVARS_IN(NSVARS)
      DOUBLE PRECISION, INTENT(OUT) :: R(NDOFEL)
      DOUBLE PRECISION, INTENT(OUT) :: K(NDOFEL,NDOFEL)
      DOUBLE PRECISION, INTENT(OUT) :: SVARS_OUT(NSVARS)
      DOUBLE PRECISION, INTENT(IN) :: TIME(2), DTIME

C     --- Local parameters ---
      INTEGER, PARAMETER :: NCORNER = 8

C     --- Nodal arrays ---
      DOUBLE PRECISION :: u_node(ndim, NNODE_E)
      DOUBLE PRECISION :: u_old(ndim, NNODE_E)
      INTEGER :: edof_u(ndim, NNODE_E)

C     --- Shape functions and mapping ---
      DOUBLE PRECISION :: sh8(8), dshxi8(8,3), dsh8(8,3)
      DOUBLE PRECISION :: xi_gp(8,3), w_gp(8)
      DOUBLE PRECISION :: coords_3d(3, NNODE_E)
      DOUBLE PRECISION :: detJxi, Jinv_xi(3,3)
      INTEGER :: ngp_out, stat

C     --- Per-GP stored data ---
      DOUBLE PRECISION :: dsh8_all(NGP, NNODE_E, 3)
      DOUBLE PRECISION :: detJxi_all(NGP)
      DOUBLE PRECISION :: F_all(3, 3, NGP)
      DOUBLE PRECISION :: J_all(NGP)
      DOUBLE PRECISION :: Finv_all(3, 3, NGP)

C     --- F-bar quantities ---
      DOUBLE PRECISION :: V0, Jbar_num, Jbar, alpha
      DOUBLE PRECISION :: Fbar(3,3), P_bar(3,3)
      DOUBLE PRECISION :: dJbar_du(ndim, NNODE_E)
      DOUBLE PRECISION :: Q_all(ndim, ndim, NGP)
      DOUBLE PRECISION :: g_ai, h_bk, wdetJ, dt_safe

C     --- CS tangent ---
      DOUBLE PRECISION :: Atang(3,3,3,3)

C     --- Complex temps for material evaluation ---
      DOUBLE COMPLEX :: Fbar_z(3,3), Pz_eval(3,3)

            DOUBLE PRECISION :: det33d
      DOUBLE COMPLEX :: det33z
      INTEGER :: idx, ii_v, jj_v, i, j, k1, l, m, N, kk, gg
      INTEGER :: row, col


C     Extract 3D coordinates
      DO ii_v = 1, NNODE_E
        coords_3d(1, ii_v) = COORDS(1, ii_v)
        coords_3d(2, ii_v) = COORDS(2, ii_v)
        coords_3d(3, ii_v) = COORDS(3, ii_v)
      END DO

C     Zero R and K
      DO i = 1, NDOFEL
        R(i) = 0.0d0
        DO j = 1, NDOFEL
          K(i, j) = 0.0d0
        END DO
      END DO

C     Carry state forward
      DO i = 1, NSVARS
        SVARS_OUT(i) = SVARS_IN(i)
      END DO

C     DTIME guard (allow DTIME=0 for initial eval)
      dt_safe = DTIME
      IF (dt_safe .LT. 1.0d-14) dt_safe = 1.0d-14

C     Parse DOFs and build edof map
      idx = 0
      DO ii_v = 1, NNODE_E
        DO i = 1, ndim
          idx = idx + 1
          u_node(i, ii_v) = U(idx)
          u_old(i, ii_v) = U(idx) - DU(idx)
          edof_u(i, ii_v) = idx
        END DO
      END DO

C     =============================================
C     Pass 1: Compute Jbar and store per-GP data
C     =============================================
      CALL gauss_hex8(xi_gp, w_gp, ngp_out)

      V0 = 0.0d0
      Jbar_num = 0.0d0

      DO kk = 1, NGP
        CALL shape_hex8(xi_gp(kk,1),
     &    xi_gp(kk,2), xi_gp(kk,3), sh8, dshxi8)
        CALL map_grad_3d(dshxi8, coords_3d, 8,
     &    dsh8, detJxi, Jinv_xi, stat)

        IF (stat .EQ. 0) THEN
          RETURN
        END IF

C       Store per-GP data
        detJxi_all(kk) = detJxi
        DO ii_v = 1, NNODE_E
          dsh8_all(kk, ii_v, 1) = dsh8(ii_v, 1)
          dsh8_all(kk, ii_v, 2) = dsh8(ii_v, 2)
          dsh8_all(kk, ii_v, 3) = dsh8(ii_v, 3)
        END DO

C       Compute F (eye33d for F33=1)
        CALL eye33d(F_all(1,1,kk))
        DO ii_v = 1, NNODE_E
          DO i = 1, ndim
            DO j = 1, ndim
              F_all(i,j,kk) = F_all(i,j,kk)
     &          + u_node(i,ii_v)*dsh8(ii_v,j)
            END DO
          END DO
        END DO

C       J and Finv
        J_all(kk) = det33d(F_all(1,1,kk))
        CALL inv33d(F_all(1,1,kk),
     &    Finv_all(1,1,kk))

C       Accumulate Jbar
        V0 = V0 + detJxi * w_gp(kk)
        Jbar_num = Jbar_num
     &    + J_all(kk) * detJxi * w_gp(kk)
      END DO

      Jbar = Jbar_num / V0

C     Compute dJbar/du (element-level sum)
      DO jj_v = 1, NNODE_E
        DO k1 = 1, ndim
          dJbar_du(k1,jj_v) = 0.0d0
          DO gg = 1, NGP
            DO N = 1, ndim
              dJbar_du(k1,jj_v) = dJbar_du(k1,jj_v)
     &          + J_all(gg)
     &          * Finv_all(N,k1,gg)
     &          * dsh8_all(gg,jj_v,N)
     &          * detJxi_all(gg)
     &          * w_gp(gg) / V0
            END DO
          END DO
        END DO
      END DO

C     =============================================
C     Pass 2: Fbar, material, R, K_std, Q
C     =============================================
      DO kk = 1, NGP
        alpha = (Jbar / J_all(kk))
     &    ** (1.0d0 / DBLE(ndim))
        wdetJ = detJxi_all(kk) * w_gp(kk)

C       Compute Fbar (in-plane only)
        CALL eye33d(Fbar)
        DO i = 1, ndim
          DO j = 1, ndim
            Fbar(i,j) = alpha * F_all(i,j,kk)
          END DO
        END DO

C       Material evaluation with Fbar
        CALL real2complex33(Fbar, Fbar_z)
        CALL neohookean_stress_PK1(
     &    Fbar_z, PROPS, Pz_eval)
        DO i = 1, 3
          DO j = 1, 3
            P_bar(i,j) = DBLE(Pz_eval(i,j))
          END DO
        END DO

C       R: r_a^i = P_bar_iJ * dN_a/dX_J * wdetJ
        DO ii_v = 1, NNODE_E
          DO i = 1, ndim
            row = edof_u(i, ii_v)
            DO j = 1, ndim
              R(row) = R(row)
     &          + P_bar(i,j)
     &          * dsh8_all(kk,ii_v,j) * wdetJ
            END DO
          END DO
        END DO

C       CS tangent: A_iJkL = dP_bar/dFbar_kL
        CALL neohookean_cs_tangent_dPdF(
     &    Fbar, PROPS, Atang)

C       Standard K (alpha-scaled)
        DO ii_v = 1, NNODE_E
          DO jj_v = 1, NNODE_E
            DO i = 1, ndim
              row = edof_u(i, ii_v)
              DO k1 = 1, ndim
                col = edof_u(k1, jj_v)
                DO j = 1, ndim
                  DO l = 1, ndim
                    K(row,col) =
     &                K(row,col)
     &                + alpha
     &                * Atang(i,j,k1,l)
     &                * dsh8_all(kk,ii_v,j)
     &                * dsh8_all(kk,jj_v,l)
     &                * wdetJ
                  END DO
                END DO
              END DO
            END DO
          END DO
        END DO

C       Q = A : Fbar (in-plane only)
        DO i = 1, ndim
          DO j = 1, ndim
            Q_all(i,j,kk) = 0.0d0
            DO m = 1, ndim
              DO N = 1, ndim
                Q_all(i,j,kk) =
     &            Q_all(i,j,kk)
     &            + Atang(i,j,m,N)
     &            * Fbar(m,N)
              END DO
            END DO
          END DO
        END DO

      END DO
C     End Pass 2

C     =============================================
C     Pass 3: F-bar correction (rank-1 update)
C     =============================================
      DO kk = 1, NGP
        wdetJ = detJxi_all(kk) * w_gp(kk)

        DO ii_v = 1, NNODE_E
          DO jj_v = 1, NNODE_E
            DO i = 1, ndim
              row = edof_u(i, ii_v)

C             g_a^i = Q_iJ * dN_a/dX_J * wdetJ
              g_ai = 0.0d0
              DO j = 1, ndim
                g_ai = g_ai
     &            + Q_all(i,j,kk)
     &            * dsh8_all(kk,ii_v,j) * wdetJ
              END DO

              DO k1 = 1, ndim
                col = edof_u(k1, jj_v)

C               h_bk = (1/ndim)*[dJbar/du/Jbar
C                       - Finv_Nk * dN_b/dX_N]
                h_bk = dJbar_du(k1,jj_v) / Jbar
                DO N = 1, ndim
                  h_bk = h_bk
     &              - Finv_all(N,k1,kk)
     &              * dsh8_all(kk,jj_v,N)
                END DO
                h_bk = h_bk
     &            / DBLE(ndim)

                K(row,col) =
     &            K(row,col)
     &            + g_ai * h_bk
              END DO
            END DO
          END DO
        END DO
      END DO
C     End Pass 3

      RETURN
      END SUBROUTINE coupfe_element_rk

C======================================================================
C     Section 2: Material subroutines (COMPLEX*16)
C     AST-translated from Python Material methods
C======================================================================
      SUBROUTINE neohookean_stress_PK1(F, props, P_out)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: F(3,3)
      DOUBLE PRECISION, INTENT(IN) :: props(2)
      DOUBLE COMPLEX, INTENT(OUT) :: P_out(3,3)

      DOUBLE COMPLEX :: det33z
      DOUBLE COMPLEX :: INV1(3,3)
      DOUBLE COMPLEX :: AT2(3,3)
      DOUBLE COMPLEX :: FinvT(3,3)
      DOUBLE COMPLEX :: J
      INTEGER :: ii, jj

      J = det33z(F)
      CALL inv33z(F, INV1)
      CALL transpose33z(INV1, AT2)
      FinvT = AT2

      DO ii = 1, 3
        DO jj = 1, 3
          P_out(ii,jj) = ((DCMPLX(props(1), 0.0d0) * (F(ii,jj) -
     &FinvT(ii,jj))) + ((DCMPLX(props(2), 0.0d0) * LOG(J)) * FinvT(ii,
     &jj)))
        END DO
      END DO

      RETURN
      END SUBROUTINE neohookean_stress_PK1


C======================================================================
C     Section 3: Complex-step tangent engine
C======================================================================
      SUBROUTINE neohookean_cs_tangent_dPdF(
     &  F, PROPS, dPdF)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: F(3,3)
      DOUBLE PRECISION, INTENT(IN) :: PROPS(2)
      DOUBLE PRECISION, INTENT(OUT) :: dPdF(3,3,3,3)

C     CS_H = 1e-10: verified for this framework
      DOUBLE PRECISION, PARAMETER :: CS_H = 1.0d-10
      DOUBLE COMPLEX :: Fz(3,3), Pz(3,3)
      INTEGER :: i, j, k, l

      DO k = 1, 3
        DO l = 1, 3
          CALL real2complex33(F, Fz)
          Fz(k,l) = Fz(k,l)
     &      + DCMPLX(0.0d0, CS_H)
          CALL neohookean_stress_PK1(
     &      Fz, PROPS, Pz)
          DO i = 1, 3
            DO j = 1, 3
              dPdF(i,j,k,l) =
     &          AIMAG(Pz(i,j)) / CS_H
            END DO
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE neohookean_cs_tangent_dPdF

C======================================================================
C     Section 4: Shipped templates (tensor ops, shape
C     functions, quadrature, isoparametric mapping)
C======================================================================
C======================================================================
C     tensor_ops.for — Complex-arithmetic tensor utilities
C
C     Provides det33, inv33, matmul33, transpose33, outer33 for
C     DOUBLE COMPLEX arguments. Also provides real-only wrappers.
C
C     Design:  1:1 mirror of Python det33/inv33 in phase0_threefield.py
C     Purpose: Foundation for complex-step tangent engine
C
C     Convention: All 3x3 matrices stored as (3,3) arrays
C                 Index order: (row, col) = (i, J)
C======================================================================

C----------------------------------------------------------------------
C     det33z: Determinant of 3x3 complex matrix
C----------------------------------------------------------------------
      FUNCTION det33z(A) RESULT(d)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: A(3,3)
      DOUBLE COMPLEX :: d

      d = A(1,1)*(A(2,2)*A(3,3) - A(2,3)*A(3,2))
     &  - A(1,2)*(A(2,1)*A(3,3) - A(2,3)*A(3,1))
     &  + A(1,3)*(A(2,1)*A(3,2) - A(2,2)*A(3,1))

      RETURN
      END FUNCTION det33z

C----------------------------------------------------------------------
C     det33d: Determinant of 3x3 real matrix
C----------------------------------------------------------------------
      FUNCTION det33d(A) RESULT(d)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: A(3,3)
      DOUBLE PRECISION :: d

      d = A(1,1)*(A(2,2)*A(3,3) - A(2,3)*A(3,2))
     &  - A(1,2)*(A(2,1)*A(3,3) - A(2,3)*A(3,1))
     &  + A(1,3)*(A(2,1)*A(3,2) - A(2,2)*A(3,1))

      RETURN
      END FUNCTION det33d

C----------------------------------------------------------------------
C     inv33z: Inverse of 3x3 complex matrix
C----------------------------------------------------------------------
      SUBROUTINE inv33z(A, Ainv)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: Ainv(3,3)
      DOUBLE COMPLEX :: d, det33z

      d = det33z(A)

      Ainv(1,1) = (A(2,2)*A(3,3) - A(2,3)*A(3,2)) / d
      Ainv(1,2) = (A(1,3)*A(3,2) - A(1,2)*A(3,3)) / d
      Ainv(1,3) = (A(1,2)*A(2,3) - A(1,3)*A(2,2)) / d
      Ainv(2,1) = (A(2,3)*A(3,1) - A(2,1)*A(3,3)) / d
      Ainv(2,2) = (A(1,1)*A(3,3) - A(1,3)*A(3,1)) / d
      Ainv(2,3) = (A(1,3)*A(2,1) - A(1,1)*A(2,3)) / d
      Ainv(3,1) = (A(2,1)*A(3,2) - A(2,2)*A(3,1)) / d
      Ainv(3,2) = (A(1,2)*A(3,1) - A(1,1)*A(3,2)) / d
      Ainv(3,3) = (A(1,1)*A(2,2) - A(1,2)*A(2,1)) / d

      RETURN
      END SUBROUTINE inv33z

C----------------------------------------------------------------------
C     inv33d: Inverse of 3x3 real matrix
C----------------------------------------------------------------------
      SUBROUTINE inv33d(A, Ainv)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: Ainv(3,3)
      DOUBLE PRECISION :: d, det33d

      d = det33d(A)

      Ainv(1,1) = (A(2,2)*A(3,3) - A(2,3)*A(3,2)) / d
      Ainv(1,2) = (A(1,3)*A(3,2) - A(1,2)*A(3,3)) / d
      Ainv(1,3) = (A(1,2)*A(2,3) - A(1,3)*A(2,2)) / d
      Ainv(2,1) = (A(2,3)*A(3,1) - A(2,1)*A(3,3)) / d
      Ainv(2,2) = (A(1,1)*A(3,3) - A(1,3)*A(3,1)) / d
      Ainv(2,3) = (A(1,3)*A(2,1) - A(1,1)*A(2,3)) / d
      Ainv(3,1) = (A(2,1)*A(3,2) - A(2,2)*A(3,1)) / d
      Ainv(3,2) = (A(1,2)*A(3,1) - A(1,1)*A(3,2)) / d
      Ainv(3,3) = (A(1,1)*A(2,2) - A(1,2)*A(2,1)) / d

      RETURN
      END SUBROUTINE inv33d

C----------------------------------------------------------------------
C     matmul33z: C = A * B for 3x3 complex matrices
C     (Explicit loop — avoids MATMUL intrinsic for portability)
C----------------------------------------------------------------------
      SUBROUTINE matmul33z(A, B, C)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3), B(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j, k

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = (0.0d0, 0.0d0)
          DO k = 1, 3
            C(i,j) = C(i,j) + A(i,k) * B(k,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE matmul33z

C----------------------------------------------------------------------
C     matmul33d: C = A * B for 3x3 real matrices
C----------------------------------------------------------------------
      SUBROUTINE matmul33d(A, B, C)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3), B(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j, k

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = 0.0d0
          DO k = 1, 3
            C(i,j) = C(i,j) + A(i,k) * B(k,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE matmul33d

C----------------------------------------------------------------------
C     transpose33z: B = A^T for 3x3 complex matrix
C----------------------------------------------------------------------
      SUBROUTINE transpose33z(A, AT)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: AT(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          AT(i,j) = A(j,i)
        END DO
      END DO

      RETURN
      END SUBROUTINE transpose33z

C----------------------------------------------------------------------
C     transpose33d: B = A^T for 3x3 real matrix
C----------------------------------------------------------------------
      SUBROUTINE transpose33d(A, AT)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: AT(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          AT(i,j) = A(j,i)
        END DO
      END DO

      RETURN
      END SUBROUTINE transpose33d

C----------------------------------------------------------------------
C     matvec33z: y = A * x for 3x3 complex matrix and 3-vector
C----------------------------------------------------------------------
      SUBROUTINE matvec33z(A, x, y)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3), x(3)
      DOUBLE COMPLEX, INTENT(OUT) :: y(3)
      INTEGER :: i, k

      DO i = 1, 3
        y(i) = (0.0d0, 0.0d0)
        DO k = 1, 3
          y(i) = y(i) + A(i,k) * x(k)
        END DO
      END DO

      RETURN
      END SUBROUTINE matvec33z

C----------------------------------------------------------------------
C     matvec33d: y = A * x for 3x3 real matrix and 3-vector
C----------------------------------------------------------------------
      SUBROUTINE matvec33d(A, x, y)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A(3,3), x(3)
      DOUBLE PRECISION, INTENT(OUT) :: y(3)
      INTEGER :: i, k

      DO i = 1, 3
        y(i) = 0.0d0
        DO k = 1, 3
          y(i) = y(i) + A(i,k) * x(k)
        END DO
      END DO

      RETURN
      END SUBROUTINE matvec33d

C----------------------------------------------------------------------
C     eye33z: A = I (3x3 complex identity)
C----------------------------------------------------------------------
      SUBROUTINE eye33z(A)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(OUT) :: A(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          IF (i .EQ. j) THEN
            A(i,j) = (1.0d0, 0.0d0)
          ELSE
            A(i,j) = (0.0d0, 0.0d0)
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE eye33z

C----------------------------------------------------------------------
C     eye33d: A = I (3x3 real identity)
C----------------------------------------------------------------------
      SUBROUTINE eye33d(A)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: A(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          IF (i .EQ. j) THEN
            A(i,j) = 1.0d0
          ELSE
            A(i,j) = 0.0d0
          END IF
        END DO
      END DO

      RETURN
      END SUBROUTINE eye33d

C----------------------------------------------------------------------
C     real2complex33: Convert real 3x3 to complex 3x3
C----------------------------------------------------------------------
      SUBROUTINE real2complex33(A_real, A_cmplx)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: A_real(3,3)
      DOUBLE COMPLEX,   INTENT(OUT) :: A_cmplx(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          A_cmplx(i,j) = DCMPLX(A_real(i,j), 0.0d0)
        END DO
      END DO

      RETURN
      END SUBROUTINE real2complex33

C----------------------------------------------------------------------
C     real2complex3: Convert real 3-vector to complex 3-vector
C----------------------------------------------------------------------
      SUBROUTINE real2complex3(v_real, v_cmplx)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: v_real(3)
      DOUBLE COMPLEX,   INTENT(OUT) :: v_cmplx(3)
      INTEGER :: i

      DO i = 1, 3
        v_cmplx(i) = DCMPLX(v_real(i), 0.0d0)
      END DO

      RETURN
      END SUBROUTINE real2complex3

C======================================================================
C     Matrix functions for tensor_ops.for
C     Eigendecomposition-based (Approach A) + iterative fallbacks (B)
C
C     All DOUBLE COMPLEX, CS-safe. See MATRIX_FUNCTIONS_DESIGN.md.
C
C     Subroutines:
C       cross3z        — cross product of complex 3-vectors
C       outer33z       — outer product of two complex 3-vectors
C       sym3z          — symmetric 3x3 tensor from 6 unique entries
C       eig33z         — eigenvalues/vectors of 3x3 symmetric matrix
C       sqrtm33z       — matrix square root via eigendecomposition
C       logm33z        — matrix logarithm via eigendecomposition
C       expm33z        — matrix exponential via eigendecomposition
C       polar33z       — right polar decomposition F = R * U
C       sqrtm33z_iter  — matrix square root (Denman-Beavers)
C       logm33z_iter   — matrix logarithm (inv scaling & squaring)
C       expm33z_iter   — matrix exponential (scaling & squaring + Pade)
C======================================================================

C----------------------------------------------------------------------
C     cross3z: Cross product of two complex 3-vectors
C----------------------------------------------------------------------
      SUBROUTINE cross3z(a, b, c)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a(3), b(3)
      DOUBLE COMPLEX, INTENT(OUT) :: c(3)

      c(1) = a(2)*b(3) - a(3)*b(2)
      c(2) = a(3)*b(1) - a(1)*b(3)
      c(3) = a(1)*b(2) - a(2)*b(1)

      RETURN
      END SUBROUTINE cross3z

C----------------------------------------------------------------------
C     outer33z: Outer product of two complex 3-vectors, C_ij = a_i b_j
C----------------------------------------------------------------------
      SUBROUTINE outer33z(a, b, C)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a(3), b(3)
      DOUBLE COMPLEX, INTENT(OUT) :: C(3,3)
      INTEGER :: i, j

      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = a(i) * b(j)
        END DO
      END DO

      RETURN
      END SUBROUTINE outer33z

C----------------------------------------------------------------------
C     sym3z: Symmetric 3x3 tensor from its 6 unique entries
C            T = [[a11, a12, a13],
C                 [a12, a22, a23],
C                 [a13, a23, a33]]
C----------------------------------------------------------------------
      SUBROUTINE sym3z(a11, a22, a33, a12, a13, a23, T)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a11, a22, a33, a12, a13, a23
      DOUBLE COMPLEX, INTENT(OUT) :: T(3,3)

      T(1,1) = a11
      T(2,2) = a22
      T(3,3) = a33
      T(1,2) = a12
      T(2,1) = a12
      T(1,3) = a13
      T(3,1) = a13
      T(2,3) = a23
      T(3,2) = a23

      RETURN
      END SUBROUTINE sym3z

C----------------------------------------------------------------------
C     eig33z: Eigenvalues and eigenvectors of 3x3 symmetric matrix
C
C     Uses trigonometric solution for the depressed cubic.
C     Eigenvectors are UNNORMALIZED (raw cross products) for CS
C     correctness. Use inv(V) not V^T for reconstruction.
C
C     KNOWN LIMITATION (audit 2026-06-10, finding H2): the degeneracy
C     guards below return lam=q, V=I and DISCARD complex-step
C     perturbations at (near-)diagonal/identity states, silently
C     zeroing CS derivatives of spectral functions there (C = F^T F
C     is exactly I at the first increment). tensor.py eig() was fixed
C     2026-06-12 with a perturbation-theory fallback; this Fortran
C     mirror has NOT been ported (needs a real-symmetric 3x3 Jacobi
C     solver). The default matrix_backend='iterative' does not call
C     eig33z; do not switch materials to backend='eig' until ported.
C----------------------------------------------------------------------
      SUBROUTINE eig33z(A, lam, V)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: lam(3), V(3,3)

C     --- Local variables ---
      DOUBLE COMPLEX :: p1, q, p2, p, r, phi
      DOUBLE COMPLEX :: B(3,3), C(3,3), M(3,3)
      DOUBLE COMPLEX :: zi, zacos, ztmp
      DOUBLE COMPLEX :: det33z
      DOUBLE COMPLEX :: r0(3), r1(3), r2(3)
      DOUBLE COMPLEX :: c1(3), c2(3), c3(3)
      DOUBLE COMPLEX :: nsq1, nsq2, nsq3, best_nsq
      DOUBLE PRECISION, PARAMETER ::
     &  PI = 3.14159265358979323846d0
      DOUBLE PRECISION :: twopi3
      INTEGER :: i, j, k, best_idx

      zi = DCMPLX(0.0d0, 1.0d0)
      twopi3 = 2.0d0 * PI / 3.0d0

C     --- Invariants ---
      p1 = A(1,2)**2 + A(1,3)**2 + A(2,3)**2
      q  = (A(1,1) + A(2,2) + A(3,3)) / 3.0d0

C     B = A - q*I
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j)
        END DO
      END DO
      B(1,1) = B(1,1) - q
      B(2,2) = B(2,2) - q
      B(3,3) = B(3,3) - q

      p2 = B(1,1)**2 + B(2,2)**2 + B(3,3)**2
     &   + 2.0d0 * p1
      p  = SQRT(p2 / 6.0d0)

C     Guard: A is a multiple of identity
      IF (ABS(p) .LT. 1.0d-30) THEN
        lam(1) = q
        lam(2) = q
        lam(3) = q
        CALL eye33z(V)
        RETURN
      END IF

C     Nearly-diagonal guard (matches Python tensor.eig)
      IF (ABS(DBLE(p2)) .GT. 0.0d0 .AND.
     &    (ABS(DBLE(p1)) .LT. 1.0d-14 * ABS(DBLE(p2)) .OR.
     &     ABS(p1) .LT. 1.0d-18)) THEN
        lam(1) = A(1,1)
        lam(2) = A(2,2)
        lam(3) = A(3,3)
        CALL eye33z(V)
        DO i = 1, 2
          DO j = i+1, 3
            IF (DBLE(lam(j)) .LT. DBLE(lam(i))) THEN
              ztmp = lam(i)
              lam(i) = lam(j)
              lam(j) = ztmp
              DO k = 1, 3
                ztmp = V(k,i)
                V(k,i) = V(k,j)
                V(k,j) = ztmp
              END DO
            END IF
          END DO
        END DO
        RETURN
      END IF

C     C = B / p
      DO i = 1, 3
        DO j = 1, 3
          C(i,j) = B(i,j) / p
        END DO
      END DO

C     r = det(C) / 2
      r = det33z(C) / 2.0d0

C     Clamp real part before complex arccos, matching tensor.py eig().
C     Near repeated eigenvalues, roundoff can push DBLE(r) just outside
C     [-1, 1] and poison complex-step tangents with NaNs.
      r = DCMPLX(MAX(-1.0d0, MIN(1.0d0, DBLE(r))), AIMAG(r))

C     Complex arccos: zacos = -i * log(r + i*sqrt(1 - r^2))
      zacos = -zi * LOG(r + zi * SQRT(
     &  DCMPLX(1.0d0, 0.0d0) - r*r))
      phi = zacos / 3.0d0

C     Three eigenvalues
      lam(1) = q + 2.0d0*p*COS(phi)
      lam(2) = q + 2.0d0*p*COS(phi
     &       + DCMPLX(twopi3, 0.0d0))
      lam(3) = q + 2.0d0*p*COS(phi
     &       + DCMPLX(2.0d0*twopi3, 0.0d0))

C     Sort by real part (ascending, 3-element bubble sort)
      DO i = 1, 2
        DO j = i+1, 3
          IF (DBLE(lam(j)) .LT. DBLE(lam(i))) THEN
            ztmp = lam(i)
            lam(i) = lam(j)
            lam(j) = ztmp
          END IF
        END DO
      END DO

C     --- Eigenvectors via cross products of rows of (A - lam*I) ---
      DO k = 1, 3
C       M = A - lam(k) * I
        DO i = 1, 3
          DO j = 1, 3
            M(i,j) = A(i,j)
          END DO
        END DO
        M(1,1) = M(1,1) - lam(k)
        M(2,2) = M(2,2) - lam(k)
        M(3,3) = M(3,3) - lam(k)

C       Extract rows
        DO j = 1, 3
          r0(j) = M(1,j)
          r1(j) = M(2,j)
          r2(j) = M(3,j)
        END DO

C       Three candidate cross products
        CALL cross3z(r0, r1, c1)
        CALL cross3z(r0, r2, c2)
        CALL cross3z(r1, r2, c3)

C       Squared norms (complex)
        nsq1 = c1(1)*c1(1) + c1(2)*c1(2) + c1(3)*c1(3)
        nsq2 = c2(1)*c2(1) + c2(2)*c2(2) + c2(3)*c2(3)
        nsq3 = c3(1)*c3(1) + c3(2)*c3(2) + c3(3)*c3(3)

C       Pick best (largest |nsq|)
        best_idx = 1
        best_nsq = nsq1
        IF (ABS(nsq2) .GT. ABS(best_nsq)) THEN
          best_idx = 2
          best_nsq = nsq2
        END IF
        IF (ABS(nsq3) .GT. ABS(best_nsq)) THEN
          best_idx = 3
          best_nsq = nsq3
        END IF

C       Store eigenvector (unnormalized for CS correctness)
        IF (ABS(best_nsq) .LT. 1.0d-50) THEN
C         Degenerate: coordinate basis fallback
          V(1,k) = DCMPLX(0.0d0, 0.0d0)
          V(2,k) = DCMPLX(0.0d0, 0.0d0)
          V(3,k) = DCMPLX(0.0d0, 0.0d0)
          V(k,k) = DCMPLX(1.0d0, 0.0d0)
        ELSE IF (best_idx .EQ. 1) THEN
          V(1,k) = c1(1)
          V(2,k) = c1(2)
          V(3,k) = c1(3)
        ELSE IF (best_idx .EQ. 2) THEN
          V(1,k) = c2(1)
          V(2,k) = c2(2)
          V(3,k) = c2(3)
        ELSE
          V(1,k) = c3(1)
          V(2,k) = c3(2)
          V(3,k) = c3(3)
        END IF
      END DO

      RETURN
      END SUBROUTINE eig33z

C----------------------------------------------------------------------
C     sqrtm33z: Matrix square root via eigendecomposition
C
C     sqrtm(A) = V * diag(sqrt(lam)) * inv(V)
C     Uses inv(V) (not V^T) for CS correctness.
C----------------------------------------------------------------------
      SUBROUTINE sqrtm33z(A, S)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: S(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(sqrt(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = SQRT(lam(1))
      D(2,2) = SQRT(lam(2))
      D(3,3) = SQRT(lam(3))

C     S = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, S)

      RETURN
      END SUBROUTINE sqrtm33z

C----------------------------------------------------------------------
C     logm33z: Matrix logarithm via eigendecomposition
C
C     logm(A) = V * diag(log(lam)) * inv(V)
C     For Hencky strain: E = 0.5 * logm(C)
C----------------------------------------------------------------------
      SUBROUTINE logm33z(A, L)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: L(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(log(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = LOG(lam(1))
      D(2,2) = LOG(lam(2))
      D(3,3) = LOG(lam(3))

C     L = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, L)

      RETURN
      END SUBROUTINE logm33z

C----------------------------------------------------------------------
C     expm33z: Matrix exponential via eigendecomposition
C
C     expm(A) = V * diag(exp(lam)) * inv(V)
C     For exponential map: Fp_new = expm(dt*Dp) * Fp_old
C----------------------------------------------------------------------
      SUBROUTINE expm33z(A, E)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: E(3,3)

      DOUBLE COMPLEX :: lam(3), V(3,3), Vinv(3,3)
      DOUBLE COMPLEX :: D(3,3), T(3,3)
      INTEGER :: i, j

      CALL eig33z(A, lam, V)
      CALL inv33z(V, Vinv)

C     D = diag(exp(lam))
      DO i = 1, 3
        DO j = 1, 3
          D(i,j) = DCMPLX(0.0d0, 0.0d0)
        END DO
      END DO
      D(1,1) = EXP(lam(1))
      D(2,2) = EXP(lam(2))
      D(3,3) = EXP(lam(3))

C     E = V * D * Vinv
      CALL matmul33z(V, D, T)
      CALL matmul33z(T, Vinv, E)

      RETURN
      END SUBROUTINE expm33z

C----------------------------------------------------------------------
C     polar33z: Right polar decomposition F = R * U
C
C     U = sqrtm(F^T * F),  R = F * inv(U)
C----------------------------------------------------------------------
      SUBROUTINE polar33z(F, R, U)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: F(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: R(3,3), U(3,3)

      DOUBLE COMPLEX :: FT(3,3), C(3,3), Uinv(3,3)

C     C = F^T * F
      CALL transpose33z(F, FT)
      CALL matmul33z(FT, F, C)

C     U = sqrtm(C)
      CALL sqrtm33z(C, U)

C     R = F * inv(U)
      CALL inv33z(U, Uinv)
      CALL matmul33z(F, Uinv, R)

      RETURN
      END SUBROUTINE polar33z

C----------------------------------------------------------------------
C     polar33z_iter: Right polar decomposition F = R * U
C
C     Iterative backend: uses sqrtm33z_iter for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE polar33z_iter(F, R, U)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: F(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: R(3,3), U(3,3)

      DOUBLE COMPLEX :: FT(3,3), C(3,3), Uinv(3,3)

C     C = F^T * F
      CALL transpose33z(F, FT)
      CALL matmul33z(FT, F, C)

C     U = sqrtm(C),  Uinv = inv(sqrtm(C))
      CALL sqrtm33z_iter(C, U, Uinv)

C     R = F * inv(U)
      CALL matmul33z(F, Uinv, R)

      RETURN
      END SUBROUTINE polar33z_iter

C----------------------------------------------------------------------
C     sqrtm33z_iter: Matrix square root via Denman-Beavers iteration
C
C     Converges: Y -> sqrtm(A),  Z -> inv(sqrtm(A))
C     Fixed iteration count for CS safety (no branching).
C----------------------------------------------------------------------
      SUBROUTINE sqrtm33z_iter(A, S, Sinv)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: S(3,3), Sinv(3,3)

      DOUBLE COMPLEX :: Y(3,3), Z(3,3)
      DOUBLE COMPLEX :: Yinv(3,3), Zinv(3,3)
      DOUBLE COMPLEX :: half
      INTEGER, PARAMETER :: MAXITER = 20
      INTEGER :: iter, i, j

      half = DCMPLX(0.5d0, 0.0d0)

C     Y = A, Z = I
      DO i = 1, 3
        DO j = 1, 3
          Y(i,j) = A(i,j)
        END DO
      END DO
      CALL eye33z(Z)

      DO iter = 1, MAXITER
        CALL inv33z(Z, Zinv)
        CALL inv33z(Y, Yinv)
        DO i = 1, 3
          DO j = 1, 3
            Y(i,j) = half * (Y(i,j) + Zinv(i,j))
            Z(i,j) = half * (Z(i,j) + Yinv(i,j))
          END DO
        END DO
      END DO

      DO i = 1, 3
        DO j = 1, 3
          S(i,j)    = Y(i,j)
          Sinv(i,j) = Z(i,j)
        END DO
      END DO

      RETURN
      END SUBROUTINE sqrtm33z_iter

C----------------------------------------------------------------------
C     logm33z_iter: Matrix logarithm via inverse scaling & squaring
C
C     Step 1: B = A^{1/2^NSCALE}  (repeated square roots)
C     Step 2: Gregory series for log(B) where B ~ I
C     Step 3: log(A) = 2^NSCALE * log(B)
C     Fixed counts for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE logm33z_iter(A, L)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: L(3,3)

      DOUBLE COMPLEX :: B(3,3), Bsqrt(3,3), Binvsqrt(3,3)
      DOUBLE COMPLEX :: BpI(3,3), BmI(3,3), BpI_inv(3,3)
      DOUBLE COMPLEX :: X(3,3), X2(3,3), Xpow(3,3)
      DOUBLE COMPLEX :: T1(3,3), II(3,3)
      DOUBLE COMPLEX :: scl
      INTEGER, PARAMETER :: NSCALE = 10
      INTEGER, PARAMETER :: NSERIES = 8
      INTEGER :: ks, i, j

C     Step 1: Repeated square roots — B = A^{1/2^NSCALE}
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j)
        END DO
      END DO
      DO ks = 1, NSCALE
        CALL sqrtm33z_iter(B, Bsqrt, Binvsqrt)
        DO i = 1, 3
          DO j = 1, 3
            B(i,j) = Bsqrt(i,j)
          END DO
        END DO
      END DO

C     Step 2: Gregory series for log(B) where B ~ I
C     X = (B - I) * inv(B + I)
      CALL eye33z(II)
      DO i = 1, 3
        DO j = 1, 3
          BpI(i,j) = B(i,j) + II(i,j)
          BmI(i,j) = B(i,j) - II(i,j)
        END DO
      END DO
      CALL inv33z(BpI, BpI_inv)
      CALL matmul33z(BmI, BpI_inv, X)

C     X2 = X * X
      CALL matmul33z(X, X, X2)

C     L = X,  Xpow = X  (start series)
      DO i = 1, 3
        DO j = 1, 3
          L(i,j)    = X(i,j)
          Xpow(i,j) = X(i,j)
        END DO
      END DO

C     L += Xpow * X2 / k  for k = 3, 5, 7, ..., 2*NSERIES+1
      DO ks = 3, 2*NSERIES+1, 2
        CALL matmul33z(Xpow, X2, T1)
        DO i = 1, 3
          DO j = 1, 3
            Xpow(i,j) = T1(i,j)
            L(i,j) = L(i,j)
     &        + Xpow(i,j) / DCMPLX(DBLE(ks), 0.0d0)
          END DO
        END DO
      END DO

C     Step 3: Undo scaling — L = 2 * L * 2^NSCALE
      scl = DCMPLX(DBLE(2**(NSCALE+1)), 0.0d0)
      DO i = 1, 3
        DO j = 1, 3
          L(i,j) = L(i,j) * scl
        END DO
      END DO

      RETURN
      END SUBROUTINE logm33z_iter

C----------------------------------------------------------------------
C     expm33z_iter: Matrix exponential via scaling & squaring + Pade
C
C     Step 1: B = A / 2^NSCALE
C     Step 2: [2/2] Pade approximant for exp(B)
C     Step 3: E = exp(B)^{2^NSCALE}  (repeated squaring)
C     Fixed counts for CS safety.
C----------------------------------------------------------------------
      SUBROUTINE expm33z_iter(A, E)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(OUT) :: E(3,3)

      DOUBLE COMPLEX :: B(3,3), B2(3,3), II(3,3)
      DOUBLE COMPLEX :: N2(3,3), D2(3,3), D2inv(3,3)
      DOUBLE COMPLEX :: T1(3,3)
      DOUBLE COMPLEX :: scl, half, twelfth
      INTEGER, PARAMETER :: NSCALE = 10
      INTEGER :: ks, i, j

      half     = DCMPLX(0.5d0, 0.0d0)
      twelfth  = DCMPLX(1.0d0/12.0d0, 0.0d0)
      scl      = DCMPLX(DBLE(2**NSCALE), 0.0d0)

C     Step 1: B = A / 2^NSCALE
      DO i = 1, 3
        DO j = 1, 3
          B(i,j) = A(i,j) / scl
        END DO
      END DO

C     B2 = B * B
      CALL matmul33z(B, B, B2)

C     [2/2] Pade: exp(B) ~ inv(I - B/2 + B^2/12) * (I + B/2 + B^2/12)
      CALL eye33z(II)
      DO i = 1, 3
        DO j = 1, 3
          N2(i,j) = II(i,j) + half*B(i,j)
     &            + twelfth*B2(i,j)
          D2(i,j) = II(i,j) - half*B(i,j)
     &            + twelfth*B2(i,j)
        END DO
      END DO
      CALL inv33z(D2, D2inv)
      CALL matmul33z(D2inv, N2, E)

C     Step 3: Repeated squaring — E = E^{2^NSCALE}
      DO ks = 1, NSCALE
        CALL matmul33z(E, E, T1)
        DO i = 1, 3
          DO j = 1, 3
            E(i,j) = T1(i,j)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE expm33z_iter

C======================================================================
C     CS-safe scalar trig/hyperbolic functions (DOUBLE COMPLEX)
C     Exact complex formulas — safe for complex-step derivatives
C======================================================================

C----------------------------------------------------------------------
C     cs_sin: complex sine  (analytic continuation of DSIN)
C----------------------------------------------------------------------
      FUNCTION cs_sin(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DSIN(x)*DCOSH(y), DCOS(x)*DSINH(y))
      RETURN
      END FUNCTION cs_sin

C----------------------------------------------------------------------
C     cs_cos: complex cosine  (analytic continuation of DCOS)
C----------------------------------------------------------------------
      FUNCTION cs_cos(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DCOS(x)*DCOSH(y), -DSIN(x)*DSINH(y))
      RETURN
      END FUNCTION cs_cos

C----------------------------------------------------------------------
C     cs_tan: complex tangent  (analytic continuation of DTAN)
C----------------------------------------------------------------------
      FUNCTION cs_tan(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y, den
      x = DBLE(z)
      y = AIMAG(z)
      den = DCOS(2.0d0*x) + DCOSH(2.0d0*y)
      w = DCMPLX(DSIN(2.0d0*x)/den, DSINH(2.0d0*y)/den)
      RETURN
      END FUNCTION cs_tan

C----------------------------------------------------------------------
C     cs_sinh: complex hyperbolic sine
C----------------------------------------------------------------------
      FUNCTION cs_sinh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DSINH(x)*DCOS(y), DCOSH(x)*DSIN(y))
      RETURN
      END FUNCTION cs_sinh

C----------------------------------------------------------------------
C     cs_cosh: complex hyperbolic cosine
C----------------------------------------------------------------------
      FUNCTION cs_cosh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(DCOSH(x)*DCOS(y), DSINH(x)*DSIN(y))
      RETURN
      END FUNCTION cs_cosh

C----------------------------------------------------------------------
C     cs_tanh: complex hyperbolic tangent
C----------------------------------------------------------------------
      FUNCTION cs_tanh(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y, den
      x = DBLE(z)
      y = AIMAG(z)
      den = DCOSH(2.0d0*x) + DCOS(2.0d0*y)
      w = DCMPLX(DSINH(2.0d0*x)/den, DSIN(2.0d0*y)/den)
      RETURN
      END FUNCTION cs_tanh

C----------------------------------------------------------------------
C     cs_erf: complex error function (CS-safe first-order approx)
C----------------------------------------------------------------------
      FUNCTION cs_erf(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE PRECISION :: x, y
      DOUBLE PRECISION, PARAMETER :: two_over_sqrt_pi =
     &  1.1283791670955126d0
      x = DBLE(z)
      y = AIMAG(z)
      w = DCMPLX(ERF(x), two_over_sqrt_pi * EXP(-x*x) * y)
      RETURN
      END FUNCTION cs_erf

C----------------------------------------------------------------------
C     cs_erfc: complex complementary error function
C----------------------------------------------------------------------
      FUNCTION cs_erfc(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      DOUBLE COMPLEX :: cs_erf
      w = DCMPLX(1.0d0, 0.0d0) - cs_erf(z)
      RETURN
      END FUNCTION cs_erfc

C----------------------------------------------------------------------
C     cs_atan: complex arctangent (analytic continuation of DATAN)
C----------------------------------------------------------------------
      FUNCTION cs_atan(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w, zi
      zi = DCMPLX(0.0D0, 1.0D0)
      w = (LOG(1.0D0 + zi*z) - LOG(1.0D0 - zi*z)) / (2.0D0*zi)
      RETURN
      END FUNCTION cs_atan

C----------------------------------------------------------------------
C     cs_acos: complex arccos  (analytic continuation of DACOS)
C----------------------------------------------------------------------
      FUNCTION cs_acos(z) RESULT(w)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN) :: z
      DOUBLE COMPLEX :: w
      w = -DCMPLX(0.0D0, 1.0D0) * LOG(z + DCMPLX(0.0D0, 1.0D0)
     &    * SQRT(1.0D0 - z**2))
      RETURN
      END FUNCTION cs_acos

C----------------------------------------------------------------------
C     cs_cubic_roots: all roots of a*x**3 + b*x**2 + c*x + d = 0
C     Depressed-cubic + Cardano, all in DOUBLE COMPLEX (CS-safe).
C----------------------------------------------------------------------
      SUBROUTINE cs_cubic_roots(a, b, c, d, r1, r2, r3)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: a, b, c, d
      DOUBLE COMPLEX, INTENT(OUT) :: r1, r2, r3
      DOUBLE COMPLEX :: p, q, Delta, sqrt_Delta, u, v, shift
      DOUBLE COMPLEX :: t1, t2, t3
      DOUBLE COMPLEX :: half, third, one, two, three, nine
      DOUBLE COMPLEX :: twentyseven

      half  = DCMPLX(0.5d0, 0.0d0)
      third = DCMPLX(1.0d0/3.0d0, 0.0d0)
      one   = DCMPLX(1.0d0, 0.0d0)
      two   = DCMPLX(2.0d0, 0.0d0)
      three = DCMPLX(3.0d0, 0.0d0)
      nine  = DCMPLX(9.0d0, 0.0d0)
      twentyseven = DCMPLX(27.0d0, 0.0d0)

C     Depress the cubic: x = t - b/(3a)
C     t**3 + p*t + q = 0
      p = (three*a*c - b*b) / (three*a*a)
      q = (two*b**3 - nine*a*b*c + twentyseven*a*a*d)
     &    / (twentyseven*a**3)

C     Discriminant
      Delta = (q/two)**2 + (p/three)**3

C     Cardano terms
      sqrt_Delta = SQRT(Delta)
      u = (-q/two + sqrt_Delta)**third
C     v chosen so that u*v = -p/3 (avoids branch-cut ambiguity).
C     Guard u=0 (triple-root / p=0 case) by computing v independently.
      IF (ABS(u) .GT. 1.0d-30) THEN
        v = -p / (three*u)
      ELSE
        v = (-q/two - sqrt_Delta)**third
      END IF

C     Three roots in t
      t1 = u + v
      t2 = -half*(u+v) + DCMPLX(0.0d0, DSQRT(3.0d0)/2.0d0)*(u-v)
      t3 = -half*(u+v) - DCMPLX(0.0d0, DSQRT(3.0d0)/2.0d0)*(u-v)

C     Shift back
      shift = b / (three*a)
      r1 = t1 - shift
      r2 = t2 - shift
      r3 = t3 - shift

      RETURN
      END SUBROUTINE cs_cubic_roots

C======================================================================
C     cs_linalg.for — CS-safe small dense linear solve
C
C     Inline LU with partial pivoting for N in {2,3,4,6,9}.
C     No LAPACK dependency — self-contained for Abaqus UMAT.
C======================================================================

C----------------------------------------------------------------------
C     cs_solve_2: solve A(2,2) * x(2) = b(2)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_2(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(2,2)
      DOUBLE COMPLEX, INTENT(IN)  :: b(2)
      DOUBLE COMPLEX, INTENT(OUT) :: x(2)
      DOUBLE COMPLEX :: LU(2,2), y(2), temp
      INTEGER :: perm(2)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 2
        perm(i) = i
        DO j = 1, 2
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 2
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 2
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 2
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 2
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 2
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 2
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 2, 1, -1
        x(i) = y(i)
        DO j = i+1, 2
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_2

C----------------------------------------------------------------------
C     cs_solve_3: solve A(3,3) * x(3) = b(3)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_3(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(3,3)
      DOUBLE COMPLEX, INTENT(IN)  :: b(3)
      DOUBLE COMPLEX, INTENT(OUT) :: x(3)
      DOUBLE COMPLEX :: LU(3,3), y(3), temp
      INTEGER :: perm(3)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 3
        perm(i) = i
        DO j = 1, 3
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 3
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 3
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 3
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 3
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 3
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 3
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 3, 1, -1
        x(i) = y(i)
        DO j = i+1, 3
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_3

C----------------------------------------------------------------------
C     cs_solve_4: solve A(4,4) * x(4) = b(4)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_4(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(4,4)
      DOUBLE COMPLEX, INTENT(IN)  :: b(4)
      DOUBLE COMPLEX, INTENT(OUT) :: x(4)
      DOUBLE COMPLEX :: LU(4,4), y(4), temp
      INTEGER :: perm(4)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 4
        perm(i) = i
        DO j = 1, 4
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 4
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 4
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 4
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 4
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 4
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 4
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 4, 1, -1
        x(i) = y(i)
        DO j = i+1, 4
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_4

C----------------------------------------------------------------------
C     cs_solve_5: solve A(5,5) * x(5) = b(5)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_5(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(5,5)
      DOUBLE COMPLEX, INTENT(IN)  :: b(5)
      DOUBLE COMPLEX, INTENT(OUT) :: x(5)
      DOUBLE COMPLEX :: LU(5,5), y(5), temp
      INTEGER :: perm(5)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 5
        perm(i) = i
        DO j = 1, 5
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 5
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 5
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 5
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 5
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 5
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 5
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 5, 1, -1
        x(i) = y(i)
        DO j = i+1, 5
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_5

C----------------------------------------------------------------------
C     cs_solve_6: solve A(6,6) * x(6) = b(6)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_6(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(6,6)
      DOUBLE COMPLEX, INTENT(IN)  :: b(6)
      DOUBLE COMPLEX, INTENT(OUT) :: x(6)
      DOUBLE COMPLEX :: LU(6,6), y(6), temp
      INTEGER :: perm(6)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 6
        perm(i) = i
        DO j = 1, 6
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 6
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 6
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 6
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 6
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 6
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 6
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 6, 1, -1
        x(i) = y(i)
        DO j = i+1, 6
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_6

C----------------------------------------------------------------------
C     cs_solve_9: solve A(9,9) * x(9) = b(9)
C----------------------------------------------------------------------
      SUBROUTINE cs_solve_9(A, b, x)
      IMPLICIT NONE
      DOUBLE COMPLEX, INTENT(IN)  :: A(9,9)
      DOUBLE COMPLEX, INTENT(IN)  :: b(9)
      DOUBLE COMPLEX, INTENT(OUT) :: x(9)
      DOUBLE COMPLEX :: LU(9,9), y(9), temp
      INTEGER :: perm(9)
      INTEGER :: i, j, k, max_row
      DOUBLE PRECISION :: max_val, abs_val

      DO i = 1, 9
        perm(i) = i
        DO j = 1, 9
          LU(i,j) = A(i,j)
        END DO
      END DO

      DO k = 1, 9
        max_val = ABS(LU(k,k))
        max_row = k
        DO i = k+1, 9
          abs_val = ABS(LU(i,k))
          IF (abs_val > max_val) THEN
            max_val = abs_val
            max_row = i
          END IF
        END DO
        IF (max_row /= k) THEN
          DO j = 1, 9
            temp = LU(k,j)
            LU(k,j) = LU(max_row,j)
            LU(max_row,j) = temp
          END DO
          j = perm(k)
          perm(k) = perm(max_row)
          perm(max_row) = j
        END IF
        DO i = k+1, 9
          LU(i,k) = LU(i,k) / LU(k,k)
          DO j = k+1, 9
            LU(i,j) = LU(i,j) - LU(i,k) * LU(k,j)
          END DO
        END DO
      END DO

      DO i = 1, 9
        y(i) = b(perm(i))
        DO j = 1, i-1
          y(i) = y(i) - LU(i,j) * y(j)
        END DO
      END DO

      DO i = 9, 1, -1
        x(i) = y(i)
        DO j = i+1, 9
          x(i) = x(i) - LU(i,j) * x(j)
        END DO
        x(i) = x(i) / LU(i,i)
      END DO
      RETURN
      END SUBROUTINE cs_solve_9

C======================================================================
C     gauss_rules.for — Gauss quadrature rules for 2D elements
C
C     Contains:
C       1. gauss_2d_2x2:  4-point (2x2), exact to degree 3
C       2. gauss_2d_3x3:  9-point (3x3), exact to degree 5
C       3. gauss_1d_2pt:  2-point edge rule, exact to degree 3
C       4. gauss_1d_3pt:  3-point edge rule, exact to degree 5
C
C     Recommended pairings:
C       Quad4 volume: 2x2
C       Quad8 volume: 3x3
C       Quad4 edge:   2pt
C       Quad8 edge:   3pt
C======================================================================

C----------------------------------------------------------------------
C     gauss_2d_2x2: 4-point Gauss quadrature (2x2)
C     Exact for polynomials up to degree 3.
C----------------------------------------------------------------------
      SUBROUTINE gauss_2d_2x2(xi_gp, w_gp, ngp)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: ngp
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(4,2), w_gp(4)

      DOUBLE PRECISION :: a
      a = 1.0d0 / DSQRT(3.0d0)

      ngp = 4

      xi_gp(1,1) = -a;  xi_gp(1,2) = -a;  w_gp(1) = 1.0d0
      xi_gp(2,1) =  a;  xi_gp(2,2) = -a;  w_gp(2) = 1.0d0
      xi_gp(3,1) =  a;  xi_gp(3,2) =  a;  w_gp(3) = 1.0d0
      xi_gp(4,1) = -a;  xi_gp(4,2) =  a;  w_gp(4) = 1.0d0

      RETURN
      END SUBROUTINE gauss_2d_2x2

C----------------------------------------------------------------------
C     gauss_2d_3x3: 9-point Gauss quadrature (3x3)
C     Exact for polynomials up to degree 5.
C     Recommended for Quad8 elements.
C----------------------------------------------------------------------
      SUBROUTINE gauss_2d_3x3(xi_gp, w_gp, ngp)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: ngp
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(9,2), w_gp(9)

      DOUBLE PRECISION :: a, w1, w2, w3
      DOUBLE PRECISION :: pts(3), wts(3)
      INTEGER :: i, j, n

      a  = DSQRT(0.6d0)
      w1 = 5.0d0 / 9.0d0
      w2 = 8.0d0 / 9.0d0
      w3 = 5.0d0 / 9.0d0

      pts(1) = -a;  wts(1) = w1
      pts(2) = 0.0d0; wts(2) = w2
      pts(3) =  a;  wts(3) = w3

      ngp = 9
      n = 0
      DO j = 1, 3
        DO i = 1, 3
          n = n + 1
          xi_gp(n,1) = pts(i)
          xi_gp(n,2) = pts(j)
          w_gp(n) = wts(i) * wts(j)
        END DO
      END DO

      RETURN
      END SUBROUTINE gauss_2d_3x3

C----------------------------------------------------------------------
C     gauss_1d_2pt: 2-point Gauss quadrature for edge integrals
C     Exact for polynomials up to degree 3.
C----------------------------------------------------------------------
      SUBROUTINE gauss_1d_2pt(xi_gp, w_gp, ngp)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: ngp
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(2), w_gp(2)

      ngp = 2
      xi_gp(1) = -1.0d0 / DSQRT(3.0d0);  w_gp(1) = 1.0d0
      xi_gp(2) =  1.0d0 / DSQRT(3.0d0);  w_gp(2) = 1.0d0

      RETURN
      END SUBROUTINE gauss_1d_2pt

C----------------------------------------------------------------------
C     gauss_1d_3pt: 3-point Gauss quadrature for edge integrals
C     Exact for polynomials up to degree 5.
C     Recommended for Quad8 edge integration.
C----------------------------------------------------------------------
      SUBROUTINE gauss_1d_3pt(xi_gp, w_gp, ngp)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: ngp
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(3), w_gp(3)

      ngp = 3
      xi_gp(1) = -DSQRT(0.6d0);  w_gp(1) = 5.0d0/9.0d0
      xi_gp(2) =  0.0d0;         w_gp(2) = 8.0d0/9.0d0
      xi_gp(3) =  DSQRT(0.6d0);  w_gp(3) = 5.0d0/9.0d0

      RETURN
      END SUBROUTINE gauss_1d_3pt

C======================================================================
C     isoparametric.for — Isoparametric mapping (2D and 3D)
C
C     Contains:
C       map_grad_2d:    Map shape function gradients (2D) + return Jinv
C       apply_jinv:     Map arbitrary dshxi using pre-computed Jinv (2D)
C       map_grad_3d:    Map shape function gradients (3D) + return Jinv
C       apply_jinv_3d:  Map arbitrary dshxi using pre-computed Jinv (3D)
C
C     For mixed-degree elements:
C       1. Call map_grad_Nd with full geometry to get dsh, detJ, Jinv
C       2. Call apply_jinv[_3d] with the SAME Jinv to map lower-degree
C          shape function derivatives
C======================================================================

C----------------------------------------------------------------------
C     map_grad_2d: Map shape function gradients from (xi,eta) to (X,Y)
C
C     Given:
C       dshxi(nNode,2)  — derivatives wrt xi, eta
C       coords(2,nNode) — nodal coordinates (X,Y for each node)
C       nNode           — number of nodes
C
C     Returns:
C       dsh(nNode,2)    — derivatives wrt X, Y
C       detJ            — determinant of the Jacobian
C       Jinv_out(2,2)   — inverse Jacobian (for reuse with apply_jinv)
C       stat            — 0 if detJ <= 0 (degenerate element)
C----------------------------------------------------------------------
      SUBROUTINE map_grad_2d(dshxi, coords, nNode, dsh, detJ,
     &                       Jinv_out, stat)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: nNode
      DOUBLE PRECISION, INTENT(IN)  :: dshxi(nNode,2), coords(2,nNode)
      DOUBLE PRECISION, INTENT(OUT) :: dsh(nNode,2), detJ
      DOUBLE PRECISION, INTENT(OUT) :: Jinv_out(2,2)
      INTEGER, INTENT(OUT) :: stat

      DOUBLE PRECISION :: Jac(2,2), detJinv
      INTEGER :: i, k

C     Compute Jacobian: J(i,j) = sum_a dN_a/dxi_i * X_j^a
      Jac(1,1) = 0.0d0
      Jac(1,2) = 0.0d0
      Jac(2,1) = 0.0d0
      Jac(2,2) = 0.0d0
      DO i = 1, 2
        DO k = 1, nNode
          Jac(i,1) = Jac(i,1) + dshxi(k,i) * coords(1,k)
          Jac(i,2) = Jac(i,2) + dshxi(k,i) * coords(2,k)
        END DO
      END DO

C     Determinant
      detJ = Jac(1,1)*Jac(2,2) - Jac(1,2)*Jac(2,1)

      IF (detJ .LE. 0.0d0) THEN
        stat = 0
        Jinv_out(1,1) = 0.0d0
        Jinv_out(1,2) = 0.0d0
        Jinv_out(2,1) = 0.0d0
        Jinv_out(2,2) = 0.0d0
        RETURN
      END IF

      stat = 1

C     Inverse of 2x2 Jacobian
      detJinv = 1.0d0 / detJ
      Jinv_out(1,1) =  Jac(2,2) * detJinv
      Jinv_out(1,2) = -Jac(1,2) * detJinv
      Jinv_out(2,1) = -Jac(2,1) * detJinv
      Jinv_out(2,2) =  Jac(1,1) * detJinv

C     Map: dN/dX = Jinv * dN/dxi
      DO k = 1, nNode
        dsh(k,1) = Jinv_out(1,1)*dshxi(k,1)+Jinv_out(1,2)*dshxi(k,2)
        dsh(k,2) = Jinv_out(2,1)*dshxi(k,1)+Jinv_out(2,2)*dshxi(k,2)
      END DO

      RETURN
      END SUBROUTINE map_grad_2d

C----------------------------------------------------------------------
C     apply_jinv: Map shape function derivatives using pre-computed Jinv
C
C     For mixed-degree elements: use the Jacobian inverse from the full
C     geometry mapping to map lower-degree shape function derivatives.
C
C     Given:
C       dshxi(nNode,2)  — derivatives wrt xi, eta
C       Jinv(2,2)       — pre-computed Jacobian inverse
C       nNode           — number of nodes
C
C     Returns:
C       dsh(nNode,2)    — derivatives wrt X, Y
C----------------------------------------------------------------------
      SUBROUTINE apply_jinv(dshxi, Jinv, nNode, dsh)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: nNode
      DOUBLE PRECISION, INTENT(IN)  :: dshxi(nNode,2), Jinv(2,2)
      DOUBLE PRECISION, INTENT(OUT) :: dsh(nNode,2)
      INTEGER :: k

      DO k = 1, nNode
        dsh(k,1) = Jinv(1,1)*dshxi(k,1) + Jinv(1,2)*dshxi(k,2)
        dsh(k,2) = Jinv(2,1)*dshxi(k,1) + Jinv(2,2)*dshxi(k,2)
      END DO

      RETURN
      END SUBROUTINE apply_jinv

C----------------------------------------------------------------------
C     map_grad_3d: Map shape function gradients from (xi,eta,zeta)
C                  to (X,Y,Z)
C
C     Given:
C       dshxi(nNode,3)  — derivatives wrt xi, eta, zeta
C       coords(3,nNode) — nodal coordinates (X,Y,Z for each node)
C       nNode           — number of nodes
C
C     Returns:
C       dsh(nNode,3)    — derivatives wrt X, Y, Z
C       detJ            — determinant of the Jacobian
C       Jinv_out(3,3)   — inverse Jacobian (for reuse with apply_jinv_3d)
C       stat            — 0 if detJ <= 0 (degenerate element)
C----------------------------------------------------------------------
      SUBROUTINE map_grad_3d(dshxi, coords, nNode, dsh, detJ,
     &                       Jinv_out, stat)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: nNode
      DOUBLE PRECISION, INTENT(IN)  :: dshxi(nNode,3), coords(3,nNode)
      DOUBLE PRECISION, INTENT(OUT) :: dsh(nNode,3), detJ
      DOUBLE PRECISION, INTENT(OUT) :: Jinv_out(3,3)
      INTEGER, INTENT(OUT) :: stat

      DOUBLE PRECISION :: Jac(3,3)
      DOUBLE PRECISION :: det33d
      INTEGER :: i, j, k

C     Compute Jacobian: J(i,j) = sum_a dN_a/dxi_i * X_j^a
      DO i = 1, 3
        DO j = 1, 3
          Jac(i,j) = 0.0d0
          DO k = 1, nNode
            Jac(i,j) = Jac(i,j) + dshxi(k,i) * coords(j,k)
          END DO
        END DO
      END DO

C     Determinant
      detJ = det33d(Jac)

      IF (detJ .LE. 0.0d0) THEN
        stat = 0
        DO i = 1, 3
          DO j = 1, 3
            Jinv_out(i,j) = 0.0d0
          END DO
        END DO
        RETURN
      END IF

      stat = 1

C     Inverse of 3x3 Jacobian
      CALL inv33d(Jac, Jinv_out)

C     Map: dN/dX_j = sum_i Jinv(j,i) * dN/dxi_i
      DO k = 1, nNode
        DO j = 1, 3
          dsh(k,j) = 0.0d0
          DO i = 1, 3
            dsh(k,j) = dsh(k,j) + Jinv_out(j,i) * dshxi(k,i)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE map_grad_3d

C----------------------------------------------------------------------
C     apply_jinv_3d: Map shape function derivatives using
C                    pre-computed 3x3 Jinv
C
C     Given:
C       dshxi(nNode,3)  — derivatives wrt xi, eta, zeta
C       Jinv(3,3)       — pre-computed Jacobian inverse
C       nNode           — number of nodes
C
C     Returns:
C       dsh(nNode,3)    — derivatives wrt X, Y, Z
C----------------------------------------------------------------------
      SUBROUTINE apply_jinv_3d(dshxi, Jinv, nNode, dsh)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: nNode
      DOUBLE PRECISION, INTENT(IN)  :: dshxi(nNode,3), Jinv(3,3)
      DOUBLE PRECISION, INTENT(OUT) :: dsh(nNode,3)
      INTEGER :: k, i, j

      DO k = 1, nNode
        DO j = 1, 3
          dsh(k,j) = 0.0d0
          DO i = 1, 3
            dsh(k,j) = dsh(k,j) + Jinv(j,i) * dshxi(k,i)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE apply_jinv_3d

C======================================================================
C     shape_hex8.for — Shape functions for 8-node hexahedral element
C
C     Node numbering (Abaqus convention):
C
C         8-------7          zeta
C        /|      /|          |  eta
C       5-------6 |          | /
C       | 4-----|-3          |/_____ xi
C       |/      |/
C       1-------2
C
C     Corner nodes at (xi,eta,zeta) = (±1,±1,±1):
C       Node 1: (-1,-1,-1)
C       Node 2: (+1,-1,-1)
C       Node 3: (+1,+1,-1)
C       Node 4: (-1,+1,-1)
C       Node 5: (-1,-1,+1)
C       Node 6: (+1,-1,+1)
C       Node 7: (+1,+1,+1)
C       Node 8: (-1,+1,+1)
C
C     Generates: shape_hex8 (combined N + dN/dxi)
C======================================================================

      SUBROUTINE shape_hex8(xi, eta, zeta, N, dNdxi)
C     8-node hexahedral shape functions and derivatives
C
C     Input:
C       xi, eta, zeta — natural coordinates in [-1,1]
C     Output:
C       N(8)      — shape function values at (xi,eta,zeta)
C       dNdxi(8,3) — dNdxi(a,i) = dN_a/dxi_i
C                     i=1: d/dxi, i=2: d/deta, i=3: d/dzeta
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)  :: xi, eta, zeta
      DOUBLE PRECISION, INTENT(OUT) :: N(8), dNdxi(8,3)

      DOUBLE PRECISION :: xp, xm, ep, em, zp, zm

      xp = 1.0d0 + xi
      xm = 1.0d0 - xi
      ep = 1.0d0 + eta
      em = 1.0d0 - eta
      zp = 1.0d0 + zeta
      zm = 1.0d0 - zeta

C     Shape function values
      N(1) = 0.125d0 * xm * em * zm
      N(2) = 0.125d0 * xp * em * zm
      N(3) = 0.125d0 * xp * ep * zm
      N(4) = 0.125d0 * xm * ep * zm
      N(5) = 0.125d0 * xm * em * zp
      N(6) = 0.125d0 * xp * em * zp
      N(7) = 0.125d0 * xp * ep * zp
      N(8) = 0.125d0 * xm * ep * zp

C     dN/dxi
      dNdxi(1,1) = -0.125d0 * em * zm
      dNdxi(2,1) =  0.125d0 * em * zm
      dNdxi(3,1) =  0.125d0 * ep * zm
      dNdxi(4,1) = -0.125d0 * ep * zm
      dNdxi(5,1) = -0.125d0 * em * zp
      dNdxi(6,1) =  0.125d0 * em * zp
      dNdxi(7,1) =  0.125d0 * ep * zp
      dNdxi(8,1) = -0.125d0 * ep * zp

C     dN/deta
      dNdxi(1,2) = -0.125d0 * xm * zm
      dNdxi(2,2) = -0.125d0 * xp * zm
      dNdxi(3,2) =  0.125d0 * xp * zm
      dNdxi(4,2) =  0.125d0 * xm * zm
      dNdxi(5,2) = -0.125d0 * xm * zp
      dNdxi(6,2) = -0.125d0 * xp * zp
      dNdxi(7,2) =  0.125d0 * xp * zp
      dNdxi(8,2) =  0.125d0 * xm * zp

C     dN/dzeta
      dNdxi(1,3) = -0.125d0 * xm * em
      dNdxi(2,3) = -0.125d0 * xp * em
      dNdxi(3,3) = -0.125d0 * xp * ep
      dNdxi(4,3) = -0.125d0 * xm * ep
      dNdxi(5,3) =  0.125d0 * xm * em
      dNdxi(6,3) =  0.125d0 * xp * em
      dNdxi(7,3) =  0.125d0 * xp * ep
      dNdxi(8,3) =  0.125d0 * xm * ep

      RETURN
      END SUBROUTINE shape_hex8

C======================================================================
C     gauss_hex.for — Gauss quadrature rules for hexahedral elements
C
C     Provides integration point coordinates and weights for:
C       - 2x2x2 (8-point)  — Hex8 full integration
C       - 3x3x3 (27-point) — Hex20 full integration
C       - 1-point           — Hex8 reduced integration
C       - 2x2x2 (8-point)  — Hex20 reduced integration
C
C     Generates: gauss_hex8, gauss_hex20, gauss_hex_reduced
C======================================================================

      SUBROUTINE gauss_hex8(xi_gp, w_gp, n_gp)
C     2x2x2 Gauss quadrature for 8-node hexahedral (full integration)
C
C     Output:
C       xi_gp(8,3) — integration point coordinates (xi,eta,zeta)
C       w_gp(8)    — integration weights
C       n_gp       — number of integration points (8)
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(8,3), w_gp(8)
      INTEGER, INTENT(OUT) :: n_gp

      DOUBLE PRECISION :: gp1
      INTEGER :: ii, jj, kk, idx

      n_gp = 8
      gp1 = 1.0d0 / DSQRT(3.0d0)

      idx = 0
      DO kk = 1, 2
        DO jj = 1, 2
          DO ii = 1, 2
            idx = idx + 1
            xi_gp(idx,1) = (-1.0d0)**(ii+1) * gp1
            xi_gp(idx,2) = (-1.0d0)**(jj+1) * gp1
            xi_gp(idx,3) = (-1.0d0)**(kk+1) * gp1
            w_gp(idx) = 1.0d0
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE gauss_hex8


      SUBROUTINE gauss_hex20(xi_gp, w_gp, n_gp)
C     3x3x3 Gauss quadrature for 20-node hexahedral (full integration)
C
C     Output:
C       xi_gp(27,3) — integration point coordinates
C       w_gp(27)    — integration weights
C       n_gp        — number of integration points (27)
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(27,3), w_gp(27)
      INTEGER, INTENT(OUT) :: n_gp

      DOUBLE PRECISION :: gp(3), wt(3)
      INTEGER :: ii, jj, kk, idx

      n_gp = 27

C     3-point Gauss rule: points and weights
      gp(1) = -DSQRT(0.6d0)
      gp(2) =  0.0d0
      gp(3) =  DSQRT(0.6d0)

      wt(1) = 5.0d0 / 9.0d0
      wt(2) = 8.0d0 / 9.0d0
      wt(3) = 5.0d0 / 9.0d0

      idx = 0
      DO kk = 1, 3
        DO jj = 1, 3
          DO ii = 1, 3
            idx = idx + 1
            xi_gp(idx,1) = gp(ii)
            xi_gp(idx,2) = gp(jj)
            xi_gp(idx,3) = gp(kk)
            w_gp(idx) = wt(ii) * wt(jj) * wt(kk)
          END DO
        END DO
      END DO

      RETURN
      END SUBROUTINE gauss_hex20


      SUBROUTINE gauss_hex_reduced(xi_gp, w_gp, n_gp)
C     1-point Gauss quadrature for reduced integration
C
C     Output:
C       xi_gp(1,3) — integration point at origin
C       w_gp(1)    — weight = 8.0 (volume of [-1,1]^3)
C       n_gp       — 1
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: xi_gp(1,3), w_gp(1)
      INTEGER, INTENT(OUT) :: n_gp

      n_gp = 1
      xi_gp(1,1) = 0.0d0
      xi_gp(1,2) = 0.0d0
      xi_gp(1,3) = 0.0d0
      w_gp(1) = 8.0d0

      RETURN
      END SUBROUTINE gauss_hex_reduced

C======================================================================
C     face_hex.for — Face shape functions for hexahedral elements
C
C     Used for integrating distributed loads (surface tractions)
C     over element faces in the Abaqus UEL NDLOAD interface.
C
C     Abaqus face numbering convention for hex elements:
C
C       Face 1: nodes on eta = -1  (1,2,6,5 for Hex8)
C       Face 2: nodes on eta = +1  (3,4,8,7 for Hex8)
C       Face 3: nodes on xi  = -1  (1,4,8,5 for Hex8)
C       Face 4: nodes on xi  = +1  (2,3,7,6 for Hex8)
C       Face 5: nodes on zeta= -1  (1,2,3,4 for Hex8)
C       Face 6: nodes on zeta= +1  (5,6,7,8 for Hex8)
C
C     Each face is a 2D surface parameterized by two of the three
C     natural coordinates (the third is fixed at ±1).
C
C     Generates: face_hex8_nodes, face_hex8_shape
C                face_hex20_nodes, face_hex20_shape
C======================================================================

      SUBROUTINE face_hex8_nodes(iface, face_nodes, n_face_nodes)
C     Return local node numbers on a given face of Hex8
C
C     Input:
C       iface — face number (1-6, Abaqus convention)
C     Output:
C       face_nodes(4) — local node numbers on this face
C       n_face_nodes  — 4
C
      IMPLICIT NONE
      INTEGER, INTENT(IN)  :: iface
      INTEGER, INTENT(OUT) :: face_nodes(4), n_face_nodes

      n_face_nodes = 4

      IF (iface .EQ. 1) THEN
C       eta = -1: nodes 1,2,6,5
        face_nodes(1) = 1
        face_nodes(2) = 2
        face_nodes(3) = 6
        face_nodes(4) = 5
      ELSE IF (iface .EQ. 2) THEN
C       eta = +1: nodes 3,4,8,7
        face_nodes(1) = 3
        face_nodes(2) = 4
        face_nodes(3) = 8
        face_nodes(4) = 7
      ELSE IF (iface .EQ. 3) THEN
C       xi = -1: nodes 1,4,8,5
        face_nodes(1) = 1
        face_nodes(2) = 4
        face_nodes(3) = 8
        face_nodes(4) = 5
      ELSE IF (iface .EQ. 4) THEN
C       xi = +1: nodes 2,3,7,6
        face_nodes(1) = 2
        face_nodes(2) = 3
        face_nodes(3) = 7
        face_nodes(4) = 6
      ELSE IF (iface .EQ. 5) THEN
C       zeta = -1: nodes 1,2,3,4
        face_nodes(1) = 1
        face_nodes(2) = 2
        face_nodes(3) = 3
        face_nodes(4) = 4
      ELSE IF (iface .EQ. 6) THEN
C       zeta = +1: nodes 5,6,7,8
        face_nodes(1) = 5
        face_nodes(2) = 6
        face_nodes(3) = 7
        face_nodes(4) = 8
      END IF

      RETURN
      END SUBROUTINE face_hex8_nodes


      SUBROUTINE face_hex8_shape(iface, s1, s2,
     &                           N_face, dNds, n_face_nodes)
C     Shape functions on a face of Hex8 (bilinear quad)
C
C     Input:
C       iface — face number (1-6)
C       s1, s2 — face natural coordinates in [-1,1]
C     Output:
C       N_face(4) — shape function values
C       dNds(4,2) — dN/ds1, dN/ds2
C       n_face_nodes — 4
C
C     The mapping from face params (s1,s2) to volume params
C     (xi,eta,zeta) depends on which face:
C       Face 1 (eta=-1): s1→xi, s2→zeta
C       Face 2 (eta=+1): s1→xi, s2→zeta
C       Face 3 (xi=-1):  s1→eta, s2→zeta
C       Face 4 (xi=+1):  s1→eta, s2→zeta
C       Face 5 (zeta=-1): s1→xi, s2→eta
C       Face 6 (zeta=+1): s1→xi, s2→eta
C
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: iface
      DOUBLE PRECISION, INTENT(IN)  :: s1, s2
      DOUBLE PRECISION, INTENT(OUT) :: N_face(4), dNds(4,2)
      INTEGER, INTENT(OUT) :: n_face_nodes

      DOUBLE PRECISION :: sp1, sm1, sp2, sm2

      n_face_nodes = 4

      sp1 = 1.0d0 + s1
      sm1 = 1.0d0 - s1
      sp2 = 1.0d0 + s2
      sm2 = 1.0d0 - s2

C     Bilinear quad shape functions on the face
      N_face(1) = 0.25d0 * sm1 * sm2
      N_face(2) = 0.25d0 * sp1 * sm2
      N_face(3) = 0.25d0 * sp1 * sp2
      N_face(4) = 0.25d0 * sm1 * sp2

C     dN/ds1
      dNds(1,1) = -0.25d0 * sm2
      dNds(2,1) =  0.25d0 * sm2
      dNds(3,1) =  0.25d0 * sp2
      dNds(4,1) = -0.25d0 * sp2

C     dN/ds2
      dNds(1,2) = -0.25d0 * sm1
      dNds(2,2) = -0.25d0 * sp1
      dNds(3,2) =  0.25d0 * sp1
      dNds(4,2) =  0.25d0 * sm1

      RETURN
      END SUBROUTINE face_hex8_shape


      SUBROUTINE face_hex20_nodes(iface, face_nodes,
     &                            n_face_nodes)
C     Return local node numbers on a given face of Hex20
C     Each face is an 8-node serendipity quad
C
C     Input:
C       iface — face number (1-6, Abaqus convention)
C     Output:
C       face_nodes(8) — local node numbers (4 corners + 4 midside)
C       n_face_nodes  — 8
C
      IMPLICIT NONE
      INTEGER, INTENT(IN)  :: iface
      INTEGER, INTENT(OUT) :: face_nodes(8), n_face_nodes

      n_face_nodes = 8

      IF (iface .EQ. 1) THEN
C       eta = -1: corners 1,2,6,5; midside 9,18,13,17
        face_nodes(1) = 1
        face_nodes(2) = 2
        face_nodes(3) = 6
        face_nodes(4) = 5
        face_nodes(5) = 9
        face_nodes(6) = 18
        face_nodes(7) = 13
        face_nodes(8) = 17
      ELSE IF (iface .EQ. 2) THEN
C       eta = +1: corners 3,4,8,7; midside 11,20,15,19
        face_nodes(1) = 3
        face_nodes(2) = 4
        face_nodes(3) = 8
        face_nodes(4) = 7
        face_nodes(5) = 11
        face_nodes(6) = 20
        face_nodes(7) = 15
        face_nodes(8) = 19
      ELSE IF (iface .EQ. 3) THEN
C       xi = -1: corners 1,4,8,5; midside 12,20,16,17
        face_nodes(1) = 1
        face_nodes(2) = 4
        face_nodes(3) = 8
        face_nodes(4) = 5
        face_nodes(5) = 12
        face_nodes(6) = 20
        face_nodes(7) = 16
        face_nodes(8) = 17
      ELSE IF (iface .EQ. 4) THEN
C       xi = +1: corners 2,3,7,6; midside 10,19,14,18
        face_nodes(1) = 2
        face_nodes(2) = 3
        face_nodes(3) = 7
        face_nodes(4) = 6
        face_nodes(5) = 10
        face_nodes(6) = 19
        face_nodes(7) = 14
        face_nodes(8) = 18
      ELSE IF (iface .EQ. 5) THEN
C       zeta = -1: corners 1,2,3,4; midside 9,10,11,12
        face_nodes(1) = 1
        face_nodes(2) = 2
        face_nodes(3) = 3
        face_nodes(4) = 4
        face_nodes(5) = 9
        face_nodes(6) = 10
        face_nodes(7) = 11
        face_nodes(8) = 12
      ELSE IF (iface .EQ. 6) THEN
C       zeta = +1: corners 5,6,7,8; midside 13,14,15,16
        face_nodes(1) = 5
        face_nodes(2) = 6
        face_nodes(3) = 7
        face_nodes(4) = 8
        face_nodes(5) = 13
        face_nodes(6) = 14
        face_nodes(7) = 15
        face_nodes(8) = 16
      END IF

      RETURN
      END SUBROUTINE face_hex20_nodes


      SUBROUTINE face_hex20_shape(iface, s1, s2,
     &                            N_face, dNds, n_face_nodes)
C     Shape functions on a face of Hex20 (8-node serendipity quad)
C
C     Input:
C       iface — face number (1-6)
C       s1, s2 — face natural coordinates in [-1,1]
C     Output:
C       N_face(8) — shape function values
C       dNds(8,2) — dN/ds1, dN/ds2
C       n_face_nodes — 8
C
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: iface
      DOUBLE PRECISION, INTENT(IN)  :: s1, s2
      DOUBLE PRECISION, INTENT(OUT) :: N_face(8), dNds(8,2)
      INTEGER, INTENT(OUT) :: n_face_nodes

      DOUBLE PRECISION :: sp1, sm1, sp2, sm2
      DOUBLE PRECISION :: s1sq, s2sq

      n_face_nodes = 8

      sp1 = 1.0d0 + s1
      sm1 = 1.0d0 - s1
      sp2 = 1.0d0 + s2
      sm2 = 1.0d0 - s2
      s1sq = 1.0d0 - s1*s1
      s2sq = 1.0d0 - s2*s2

C     Corner nodes (serendipity)
      N_face(1) = 0.25d0*sm1*sm2*(-s1-s2-1.0d0)
      N_face(2) = 0.25d0*sp1*sm2*( s1-s2-1.0d0)
      N_face(3) = 0.25d0*sp1*sp2*( s1+s2-1.0d0)
      N_face(4) = 0.25d0*sm1*sp2*(-s1+s2-1.0d0)

C     Midside nodes
      N_face(5) = 0.5d0*s1sq*sm2
      N_face(6) = 0.5d0*sp1*s2sq
      N_face(7) = 0.5d0*s1sq*sp2
      N_face(8) = 0.5d0*sm1*s2sq

C     dN/ds1
      dNds(1,1) = 0.25d0*sm2*( 2.0d0*s1+s2)
      dNds(2,1) = 0.25d0*sm2*( 2.0d0*s1-s2)
      dNds(3,1) = 0.25d0*sp2*( 2.0d0*s1+s2)
      dNds(4,1) = 0.25d0*sp2*( 2.0d0*s1-s2)
      dNds(5,1) = -s1*sm2
      dNds(6,1) =  0.5d0*s2sq
      dNds(7,1) = -s1*sp2
      dNds(8,1) = -0.5d0*s2sq

C     dN/ds2
      dNds(1,2) = 0.25d0*sm1*( s1+2.0d0*s2)
      dNds(2,2) = 0.25d0*sp1*(-s1+2.0d0*s2)
      dNds(3,2) = 0.25d0*sp1*( s1+2.0d0*s2)
      dNds(4,2) = 0.25d0*sm1*(-s1+2.0d0*s2)
      dNds(5,2) = -0.5d0*s1sq
      dNds(6,2) = -sp1*s2
      dNds(7,2) =  0.5d0*s1sq
      dNds(8,2) = -sm1*s2

      RETURN
      END SUBROUTINE face_hex20_shape


      SUBROUTINE face_gauss_2x2(s1_gp, s2_gp, w_gp, n_gp)
C     2x2 Gauss quadrature on a face (for Hex8 faces)
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: s1_gp(4), s2_gp(4), w_gp(4)
      INTEGER, INTENT(OUT) :: n_gp

      DOUBLE PRECISION :: gp1

      n_gp = 4
      gp1 = 1.0d0 / DSQRT(3.0d0)

      s1_gp(1) = -gp1;  s2_gp(1) = -gp1;  w_gp(1) = 1.0d0
      s1_gp(2) =  gp1;  s2_gp(2) = -gp1;  w_gp(2) = 1.0d0
      s1_gp(3) =  gp1;  s2_gp(3) =  gp1;  w_gp(3) = 1.0d0
      s1_gp(4) = -gp1;  s2_gp(4) =  gp1;  w_gp(4) = 1.0d0

      RETURN
      END SUBROUTINE face_gauss_2x2


      SUBROUTINE face_gauss_3x3(s1_gp, s2_gp, w_gp, n_gp)
C     3x3 Gauss quadrature on a face (for Hex20 faces)
C
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(OUT) :: s1_gp(9), s2_gp(9), w_gp(9)
      INTEGER, INTENT(OUT) :: n_gp

      DOUBLE PRECISION :: gp(3), wt(3)
      INTEGER :: ii, jj, idx

      n_gp = 9

      gp(1) = -DSQRT(0.6d0)
      gp(2) =  0.0d0
      gp(3) =  DSQRT(0.6d0)

      wt(1) = 5.0d0 / 9.0d0
      wt(2) = 8.0d0 / 9.0d0
      wt(3) = 5.0d0 / 9.0d0

      idx = 0
      DO jj = 1, 3
        DO ii = 1, 3
          idx = idx + 1
          s1_gp(idx) = gp(ii)
          s2_gp(idx) = gp(jj)
          w_gp(idx) = wt(ii) * wt(jj)
        END DO
      END DO

      RETURN
      END SUBROUTINE face_gauss_3x3
