# SPDX-FileCopyrightText: 2026 Teng Zhang
# SPDX-License-Identifier: MIT
"""Generate a small-strain J2 UMAT with linear isotropic hardening."""

from __future__ import annotations

import math
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import coupfe.codegen as au
from coupfe.codegen.core.small_strain_plasticity import (
    flow_direction,
    q_mises,
)
from coupfe.codegen.core.tensor import eye, trace


class SmallStrainJ2(au.SmallStrainMaterial):
    """Compression-positive radial-return J2 plasticity.

    ``PROPS`` order is ``G, lam, sigma_y, H``. ``STATEV(1)`` stores the
    equivalent plastic strain ``ep``.
    """

    props = dict(G=10.0, lam=20.0, sigma_y=0.1, H=5.0)
    state_vars = dict(ep=0.0)

    def stress_update(self, sigma_old, strain_old, dstrain, ep_old, dt):
        sigma_trial = (
            sigma_old
            + 2.0 * self.G * dstrain
            + self.lam * trace(dstrain) * eye(3)
        )
        seq = q_mises(sigma_trial)
        yield_function = seq - (self.sigma_y + self.H * ep_old)

        if yield_function.real > 0.0:
            dgamma = yield_function / (3.0 * self.G + self.H)
            direction = flow_direction(sigma_trial, seq)
            sigma_new = sigma_trial - 2.0 * self.G * dgamma * direction
            ep_new = ep_old + dgamma
        else:
            sigma_new = sigma_trial
            ep_new = ep_old

        return sigma_new, {"ep": ep_new}


FINAL_TENSOR_SHEAR = 0.02
N_INCREMENTS = 40

_GENERATED_PROVENANCE = """\
C     Declaration origin: tengzhang48/abaqus_ufl small_strain_j2_umat
C     Commit: 0f525339db1aad70e9f8f4825a02c1164f0da7a0
C     Original declaration Copyright (c) 2026 Teng Zhang, MIT.
C     Regenerated by CoupFE; see README.md for scope and license link.
"""


def closed_form_monotonic_shear(tensor_shear, material=None):
    """Independent proportional-loading solution ``(tau, ep)``."""
    mat = SmallStrainJ2() if material is None else material
    elastic_tau = 2.0 * mat.G * tensor_shear
    if math.sqrt(3.0) * elastic_tau <= mat.sigma_y:
        return elastic_tau, 0.0
    ep = (
        2.0 * math.sqrt(3.0) * mat.G * tensor_shear - mat.sigma_y
    ) / (3.0 * mat.G + mat.H)
    tau = (mat.sigma_y + mat.H * ep) / math.sqrt(3.0)
    return tau, ep


def drive_monotonic_shear(model, tensor_shear, n_increments):
    """Drive the Python update incrementally through proportional shear."""
    increment = tensor_shear / n_increments
    dstrain = np.zeros((3, 3))
    dstrain[0, 1] = dstrain[1, 0] = increment
    sigma = np.zeros((3, 3))
    strain = np.zeros((3, 3))
    ep = 0.0
    for _ in range(n_increments):
        sigma, state = model.stress_update(
            sigma, strain, dstrain, ep, 1.0 / n_increments
        )
        sigma = np.real(np.asarray(sigma, dtype=complex))
        ep = float(np.real(state["ep"]))
        strain = strain + dstrain
    return sigma, ep


def reference_errors(model=None):
    """Return elastic/plastic errors against the hand-derived shear oracle."""
    mat = SmallStrainJ2() if model is None else model
    yield_shear = mat.sigma_y / (2.0 * math.sqrt(3.0) * mat.G)

    elastic_shear = 0.5 * yield_shear
    elastic_sigma, elastic_ep = drive_monotonic_shear(
        mat, elastic_shear, 10
    )
    elastic_tau_ref, elastic_ep_ref = closed_form_monotonic_shear(
        elastic_shear, mat
    )

    plastic_sigma, plastic_ep = drive_monotonic_shear(
        mat, FINAL_TENSOR_SHEAR, N_INCREMENTS
    )
    plastic_tau_ref, plastic_ep_ref = closed_form_monotonic_shear(
        FINAL_TENSOR_SHEAR, mat
    )
    return {
        "elastic_tau_abs": abs(elastic_sigma[0, 1] - elastic_tau_ref),
        "elastic_ep_abs": abs(elastic_ep - elastic_ep_ref),
        "plastic_tau_abs": abs(plastic_sigma[0, 1] - plastic_tau_ref),
        "plastic_ep_abs": abs(plastic_ep - plastic_ep_ref),
        "plastic_ep": plastic_ep,
    }


def generate(output=None, *, verify=True) -> Path:
    """Verify the model/oracle and generate the Abaqus UMAT."""
    model = SmallStrainJ2()
    if verify:
        if not model.verify(verbose=False):
            raise RuntimeError("Python tangent verification failed")
        errors = reference_errors(model)
        if max(
            errors["elastic_tau_abs"],
            errors["elastic_ep_abs"],
            errors["plastic_tau_abs"],
            errors["plastic_ep_abs"],
        ) >= 1.0e-10:
            raise RuntimeError("independent shear oracle failed: {}".format(errors))

    target = (
        Path(__file__).with_name("small_strain_j2.for")
        if output is None
        else Path(output)
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    au.generate_small_strain_umat(model, str(target))

    source = target.read_text()
    header_end = "C======================================================================\n"
    if _GENERATED_PROVENANCE not in source:
        source = source.replace(
            header_end, header_end + _GENERATED_PROVENANCE, 1
        )
        target.write_text(source)
    return target


if __name__ == "__main__":
    print("Generated {}".format(generate()))
