"""Focused gates for the RESEARCH pressure-gel morphing Hex8 declaration."""
from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("sympy")

_ROOT = Path(__file__).parent.parent
_EXAMPLE_DIR = _ROOT / "examples" / "morphing_hex8"
_BUILD_PY = _EXAMPLE_DIR / "build.py"


def _load_example():
    spec = importlib.util.spec_from_file_location(
        "morphing_hex8_build", _BUILD_PY
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _numpy_oracle(props, F, p, mu, grad_mu, F_old, p_old, dt):
    """Independent direct-NumPy transcription of the constitutive equations."""

    G, K, chi, D, mu0, omega, rgas, theta, phi0 = props
    J = np.linalg.det(F)
    J_old = np.linalg.det(F_old)
    Je = np.exp(p / K)
    Je_old = np.exp(p_old / K)
    phi = phi0 * Je / J

    FinvT = np.linalg.inv(F).T
    stress = G * (F - FinvT) + p * FinvT
    pressure_resid = (
        mu
        - mu0
        - rgas * theta * (np.log(1.0 - phi) + phi + chi * phi**2)
        + (phi / phi0) * omega * p
    )

    Cinv = np.linalg.inv(F.T @ F)
    cR0 = (1.0 - phi0) / omega
    cR = cR0 + (phi0 - phi) / (omega * phi)
    mobility = D * cR / (rgas * theta)
    flux = -mobility * (Cinv @ grad_mu)
    storage = (J / Je - J_old / Je_old) / (omega * dt)
    return stress, pressure_resid, flux, storage, mobility


def test_material_matches_independent_oracle_and_flux_broken_control():
    ex = _load_example()
    material = ex.PressureGelMaterial()
    state = ex.verification_state()
    props = (
        1.0,
        100.0,
        0.1,
        5.0e-9,
        0.0,
        1.0e-4,
        8.314,
        298.0,
        0.5,
    )
    assert ex.DEFAULT_PROPS == props

    expected = _numpy_oracle(props, **state)
    stress, pressure_resid, flux, storage, mobility = expected

    assert np.allclose(
        material.stress_PK1(state["F"], state["p"], state["mu"]),
        stress,
        rtol=2.0e-13,
        atol=2.0e-13,
    )
    assert np.isclose(
        material.pressure_resid(state["F"], state["p"], state["mu"]),
        pressure_resid,
        rtol=2.0e-13,
        atol=2.0e-13,
    )
    actual_flux = material.solvent_flux(
        state["F"], state["p"], state["mu"], state["grad_mu"]
    )
    assert np.allclose(actual_flux, flux, rtol=2.0e-13, atol=2.0e-13)
    assert np.isclose(
        material.solvent_storage(
            state["F"],
            state["F_old"],
            state["p"],
            state["p_old"],
            state["dt"],
        ),
        storage,
        rtol=2.0e-13,
        atol=2.0e-13,
    )

    # Positive mobility requires downhill transport in the C^{-1} metric.
    metric_gradient = np.linalg.inv(state["F"].T @ state["F"]) @ state[
        "grad_mu"
    ]
    assert mobility > 0.0
    assert np.dot(actual_flux, metric_gradient) < 0.0

    # Bounded broken control: reversing the constitutive flux sign is uphill.
    reversed_flux = -actual_flux
    assert np.dot(reversed_flux, metric_gradient) > 0.0
    assert np.linalg.norm(reversed_flux - flux) > np.linalg.norm(flux)


def test_problem_verifies():
    ex = _load_example()
    assert ex.PressureGelLocalPressureHex8().verify(
        state=ex.verification_state(), verbose=False
    )


def test_generate_and_object_compile(tmp_path):
    ex = _load_example()
    for_path = ex.generate_source(str(tmp_path))

    source = for_path.read_text()
    retained_source = (
        _EXAMPLE_DIR / "pressuregel_local_pressure_hex8.for"
    ).read_text()
    assert source == retained_source
    assert "Generated by coupfe.codegen" in source
    assert "Original declaration Copyright (c) 2026 Teng Zhang, MIT." in source
    assert "Element: Hex8, NDOFEL = 32" in source
    assert "SUBROUTINE UEL" in source

    compiler = shutil.which("gfortran")
    if compiler is None:
        pytest.skip("gfortran not available")

    result = subprocess.run(
        [
            compiler,
            "-c",
            "-ffixed-form",
            "-ffixed-line-length-none",
            str(for_path),
        ],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "pressuregel_local_pressure_hex8.o").is_file()


def test_evidence_record_keeps_claim_at_current_checks():
    record = json.loads((_EXAMPLE_DIR / "evidence_record.json").read_text())
    assert record["status"] == "RESEARCH"
    assert "contact behavior" in record["not_established"]
    assert "paper Figure 6 reproduction" in record["not_established"]
    assert "Abaqus decks" in record["excluded_artifacts"]
