# SPDX-FileCopyrightText: 2026 Teng Zhang
# SPDX-License-Identifier: MIT
"""Generate a compressible neo-Hookean finite-strain Abaqus UMAT.

This is a namespace-only port of the project-authored MIT example released in
``tengzhang48/abaqus_ufl``.  It uses the public ``coupfe.codegen`` material and
UMAT generator APIs; it does not add or change any CoupFE core/runtime API.
"""
from __future__ import annotations

from pathlib import Path
import sys
from typing import Optional

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import coupfe.codegen as au
from coupfe.codegen.core.tensor import det, inv, log


class NeoHookean(au.Material):
    """Compressible neo-Hookean law with ``PROPS = (G, K)``.

    ``K`` is physical small-strain bulk modulus, so the ``ln(J)`` coefficient
    is ``lambda = K - 2G/3``.
    """

    props = dict(G=0.5, K=50.0)

    def stress_PK1(self, F):
        J = det(F)
        FinvT = inv(F).T
        lame_lambda = self.K - 2.0 * self.G / 3.0
        return self.G * (F - FinvT) + lame_lambda * log(J) * FinvT


DEFAULT_PROPS = tuple(NeoHookean.props.values())

_GENERATED_PROVENANCE = """\
C     Declaration origin: tengzhang48/abaqus_ufl neo_hookean_umat
C     Commit: 0f525339db1aad70e9f8f4825a02c1164f0da7a0
C     Original declaration Copyright (c) 2026 Teng Zhang, MIT.
C     Regenerated by CoupFE; see README.md for scope and license link.
"""


def verification_state():
    """Return a positive-J state that exercises normal and shear response."""

    return {
        "F": np.array(
            [
                [1.08, 0.06, 0.01],
                [0.02, 0.97, 0.03],
                [0.00, 0.02, 1.04],
            ]
        )
    }


def generate_source(
    output_dir: Optional[str] = None, *, verify: bool = True
) -> Path:
    """Verify the declaration and emit the self-contained Abaqus UMAT."""

    model = NeoHookean()
    if verify and not model.verify(state=verification_state(), verbose=False):
        raise RuntimeError("neo-Hookean material verification failed")

    out_dir = (
        Path(output_dir)
        if output_dir is not None
        else Path(__file__).resolve().parent
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    output = out_dir / "neo_hookean_umat.for"
    au.generate_umat(model, str(output))

    source = output.read_text()
    header_end = "C======================================================================\n"
    if _GENERATED_PROVENANCE not in source:
        source = source.replace(
            header_end, header_end + _GENERATED_PROVENANCE, 1
        )
        output.write_text(source)
    return output


if __name__ == "__main__":
    print("Generated {}".format(generate_source()))
