# SPDX-FileCopyrightText: 2026 Teng Zhang
# SPDX-License-Identifier: MIT
"""Generate the pressure-gel Hex8 UEL used by the morphing paper example.

Status: RESEARCH.  This file ports the project-authored MIT declaration from
``tengzhang48/abaqus_ufl`` commit
``0f525339db1aad70e9f8f4825a02c1164f0da7a0`` to ``coupfe.codegen``.

Original declaration: Copyright (c) 2026 Teng Zhang, MIT License.
Exact source and license links are recorded in this directory's README.
The port changes the package namespace and adds a reusable verification state
and output-directory helper; it does not copy the historical Abaqus deck,
archived submitted source, mesh, figures, or contact setup.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np

import coupfe.codegen as au
from coupfe.codegen.core.tensor import det, exp, inv, log
from coupfe.codegen.generators.uel_gen import generate_uel


class PressureGelMaterial(au.Material):
    """Pressure-coupled gel: network elasticity and Flory-Huggins mixing."""

    props = dict(
        G=1.0,
        K=100.0,
        chi=0.1,
        D=5.0e-9,
        mu0=0.0,
        Omega=1.0e-4,
        Rgas=8.314,
        theta=298.0,
        phi0=0.5,
    )

    def stress_PK1(self, F, p, mu):
        return self.G * (F - inv(F).T) + p * inv(F).T

    def pressure_resid(self, F, p, mu):
        J = det(F)
        Je = exp(p / self.K)
        phi = self.phi0 * Je / J
        return (
            mu
            - self.mu0
            - self.Rgas
            * self.theta
            * (log(1.0 - phi) + phi + self.chi * phi**2)
            + (phi / self.phi0) * self.Omega * p
        )

    def solvent_flux(self, F, p, mu, grad_mu):
        J = det(F)
        Je = exp(p / self.K)
        phi = self.phi0 * Je / J
        Cinv = inv(F.T @ F)
        cR0 = (1.0 - self.phi0) / self.Omega
        cR = cR0 + (self.phi0 - phi) / (self.Omega * phi)
        mobility = self.D * cR / (self.Rgas * self.theta)
        return -mobility * (Cinv @ grad_mu)

    def solvent_storage(self, F, F_old, p, p_old, dt):
        J = det(F)
        J_old = det(F_old)
        Je = exp(p / self.K)
        Je_old = exp(p_old / self.K)
        return (J / Je - J_old / Je_old) / (self.Omega * dt)


class PressureGelLocalPressureHex8(au.WeakForm):
    """Hex8 with global displacement/chemical potential and local pressure."""

    material = PressureGelMaterial
    ndim = 3

    def define_fields(self):
        self.u = au.VectorField("u", degree=1)
        self.mu = au.ScalarField("mu", degree=1)
        self.p = au.LocalScalar(
            "p", storage="SVARS", condensed=True, initial=0.0
        )

    def momentum_equation(self, v, F, p, mu):
        return self.material.stress_PK1(F, p, mu)

    def pressure_equation(self, q, F, p, mu):
        return self.material.pressure_resid(F, p, mu)

    def transport_equation(
        self, w, F, p, mu, grad_mu, F_old, p_old, dt
    ):
        c_dot = self.material.solvent_storage(F, F_old, p, p_old, dt)
        j_R = self.material.solvent_flux(F, p, mu, grad_mu)
        return c_dot, j_R


DEFAULT_PROPS = tuple(PressureGelMaterial.props.values())

_GENERATED_PROVENANCE = """\
C     Declaration origin: tengzhang48/abaqus_ufl pipeline_hex8.py
C     Commit: 0f525339db1aad70e9f8f4825a02c1164f0da7a0
C     Original declaration Copyright (c) 2026 Teng Zhang, MIT.
C     Regenerated by CoupFE; see README.md for scope and license link.
"""


def verification_state():
    """Return a non-degenerate three-dimensional constitutive state."""

    F = np.array(
        [
            [1.08, 0.04, 0.02],
            [0.01, 1.03, 0.03],
            [0.02, 0.01, 1.05],
        ]
    )
    return dict(
        F=F,
        F_old=0.99 * F,
        p=2.0,
        p_old=1.8,
        mu=-900.0,
        grad_mu=np.array([2.0, -1.0, 0.5]),
        dt=0.1,
    )


def generate_source(output_dir: Optional[str] = None) -> Path:
    """Verify the declaration and emit the current CoupFE Abaqus UEL."""

    problem = PressureGelLocalPressureHex8()
    if not problem.verify(state=verification_state(), verbose=False):
        raise RuntimeError("pressure-gel material verification failed")

    out_dir = Path(output_dir) if output_dir else Path(__file__).resolve().parent
    out_dir.mkdir(parents=True, exist_ok=True)
    for_path = out_dir / "pressuregel_local_pressure_hex8.for"
    generate_uel(
        problem,
        str(for_path),
        element="Hex8",
        formulation="local_pressure",
        mat_prefix="pressuregel",
    )
    source = for_path.read_text()
    header_end = "C======================================================================\n"
    if _GENERATED_PROVENANCE not in source:
        source = source.replace(
            header_end, header_end + _GENERATED_PROVENANCE, 1
        )
        for_path.write_text(source)
    return for_path


if __name__ == "__main__":
    print(f"Generated {generate_source()}")
